/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaPresentacion;

import DTOs.BoletoDTO;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.ImageIcon;
import utilitades.Utilerias;

/**
 *
 * @author Abraham Coronel Bringas
 */
public class DetalleDelBoleto extends javax.swing.JFrame {
    /*Instancia que nos permite llamar los metodos de control*/
    private ControlDeNavegacion control = ControlDeNavegacion.getInstancia();
    /*Objeto que nos permite invocar a los metodos de utilidades*/
    private Utilerias utilerias = new Utilerias();
    /**
     * Creates new form DetalleDelBoleto
     */
    
    /*Constructor de la clase DetalleDelBoleto*/
    public DetalleDelBoleto(){
        initComponents();
        
        BoletoDTO boleto = control.cargarBoleto();
        if (boleto == null) {
            dispose();
        }
        llenarCamposBoleto(boleto);
        btnRegresoMenu.setVisible(false);
        setVisible(true);
        
        //Thread.sleep(500); Esta linea sirve para que el hilo principal tena un delay de 500 milisegundos y asi se pueda tomar bien la captura de la imagen
        
        //Esta parte servira para la creacion del codigo qr
//        URL url = DetalleDelBoleto.class.getResource("img/captura.png");
//        String rutaImagen = utilerias.sacarCapturaJFrame(this, url);
//        ImageIcon qrIcon = utilerias.obtenerQRDesdeImagen(rutaImagen, 200);
//        etiquetaImagenQR.setIcon(qrIcon);
        
        btnRegresoMenu.setVisible(true);
        
        revalidate();
        repaint();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAsiento1 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        labelPelicula = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelSala = new javax.swing.JLabel();
        labelAsiento = new javax.swing.JLabel();
        btnRegresoMenu = new javax.swing.JButton();
        etiquetaImagenQR = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        etiquetaImagen = new javax.swing.JLabel();

        labelAsiento1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        labelAsiento1.setText("Asiento/s:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(640, 830));

        Titulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 64)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("DETALLES DEL BOLETO");

        labelPelicula.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        labelPelicula.setText("Pelicula: ");

        labelHora.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        labelHora.setText("Hora:");

        labelFecha.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        labelFecha.setText("Fecha:");

        labelSala.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        labelSala.setText("Sala:");

        labelAsiento.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        labelAsiento.setText("Asiento/s:");

        btnRegresoMenu.setBackground(new java.awt.Color(162, 132, 94));
        btnRegresoMenu.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnRegresoMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresoMenu.setText("Volver al menu principal");
        btnRegresoMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRegresoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresoMenuMouseClicked(evt);
            }
        });

        labelCliente.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        labelCliente.setText("Cliente: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(etiquetaImagenQR, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCliente)
                            .addComponent(labelAsiento)
                            .addComponent(labelFecha)
                            .addComponent(labelSala)
                            .addComponent(labelHora)
                            .addComponent(labelPelicula))
                        .addGap(223, 223, 223))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnRegresoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(etiquetaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(392, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Titulo)
                .addGap(70, 70, 70)
                .addComponent(labelPelicula)
                .addGap(39, 39, 39)
                .addComponent(labelFecha)
                .addGap(35, 35, 35)
                .addComponent(labelHora)
                .addGap(34, 34, 34)
                .addComponent(labelSala)
                .addGap(36, 36, 36)
                .addComponent(labelAsiento)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(etiquetaImagenQR, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(labelCliente)
                        .addGap(159, 159, 159)
                        .addComponent(btnRegresoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(173, 173, 173)
                    .addComponent(etiquetaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(477, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresoMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresoMenuMouseClicked
        // TODO add your handling code here:
        control.mostrarMenuPrincipal();
        dispose();
    }//GEN-LAST:event_btnRegresoMenuMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnRegresoMenu;
    private javax.swing.JLabel etiquetaImagen;
    private javax.swing.JLabel etiquetaImagenQR;
    private javax.swing.JLabel labelAsiento;
    private javax.swing.JLabel labelAsiento1;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelPelicula;
    private javax.swing.JLabel labelSala;
    // End of variables declaration//GEN-END:variables
    
    /*Metodo que llena los campos que requiere el boleto seteando cada atributo en un label*/
    public void llenarCamposBoleto(BoletoDTO boleto) {
        
        ImageIcon imagen = utilerias.crearImagen(boleto.getImagenPelicula(), 200, 300);
        etiquetaImagen.setIcon(imagen);
        
        labelPelicula.setText("Pelicula: " + boleto.getNombrePelicula());
        LocalDate fecha = boleto.getFechaHoraFuncion().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        labelFecha.setText("Fecha: " + utilerias.traducirDia(fecha.getDayOfWeek()) + ", " + 
                                    fecha.getDayOfMonth() + " de " + 
                                    utilerias.traducirMes(fecha.getMonth()));
        
        String funcionMinutos = (boleto.getFechaHoraFuncion().getMinutes() < 10) ? "0" + 
                Integer.toString(boleto.getFechaHoraFuncion().getMinutes()) : 
                Integer.toString(boleto.getFechaHoraFuncion().getMinutes());
        
        labelHora.setText("Hora: " + boleto.getFechaHoraFuncion().getHours() + ":" + funcionMinutos);
        
        labelSala.setText("Sala: " + boleto.getNumeroSala());
        
        String numAsientos = String.join(", ", boleto.getListaAsientosSeleccionados());
        labelAsiento.setText("Asiento/s: " + numAsientos);
        
        labelCliente.setText("Cliente: " + boleto.getNombreCliente());
    }
}
