/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaPresentacion;

import DTOs.BoletoDTO;
import DTOs.FuncionDTO;
import DTOs.PeliculaDTO;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.ImageIcon;

/**
 *
 * @author Abraham Coronel Bringas
 */
public class DetalleDelBoleto extends javax.swing.JFrame {
    
    private ControlDeNavegacion control = ControlDeNavegacion.getInstancia();
    /**
     * Creates new form DetalleDelBoleto
     */
    public DetalleDelBoleto(BoletoDTO boleto) {
        initComponents();
        
        ImageIcon imagen = control.crearImagen(boleto.getImagenPelicula(), 200, 300);
        etiquetaImagen.setIcon(imagen);
        textoPelicula.setText(boleto.getNombrePelicula());
        LocalDate fecha = boleto.getFechaHoraFuncion().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        textoFecha3.setText(control.traducirDia(fecha.getDayOfWeek()) + ", " + 
                                    fecha.getDayOfMonth() + " de " + 
                                    control.traducirMes(fecha.getMonth()));
        
        String funcionMinutos = (boleto.getFechaHoraFuncion().getMinutes() < 10) ? "0" + 
                Integer.toString(boleto.getFechaHoraFuncion().getMinutes()) : 
                Integer.toString(boleto.getFechaHoraFuncion().getMinutes());
        labelHora.setText("Hora: " + boleto.getFechaHoraFuncion().getHours() + ":" + funcionMinutos);
        
        labelSala.setText("Sala: " + boleto.getNumeroSala());
        
        String numAsientos = String.join(", ", boleto.getListaAsientosSeleccionados());
        textoAsiento.setText(numAsientos);
        
        labelCliente.setText("Cliente: " + boleto.getNombreCliente());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAsiento1 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        laberPelicula = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        labelFecha1 = new javax.swing.JLabel();
        labelSala = new javax.swing.JLabel();
        labelAsiento = new javax.swing.JLabel();
        textoPelicula = new javax.swing.JLabel();
        textoHora = new javax.swing.JLabel();
        textoSala = new javax.swing.JLabel();
        textoAsiento = new javax.swing.JLabel();
        textoFecha3 = new javax.swing.JLabel();
        btnRegresoMenu = new javax.swing.JButton();
        etiquetaImagen = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();

        labelAsiento1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        labelAsiento1.setText("Asiento/s:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(640, 830));

        Titulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 64)); // NOI18N
        Titulo.setText("DETALLES DEL BOLETO");

        laberPelicula.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        laberPelicula.setText("Pelicula: ");

        labelHora.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        labelHora.setText("Hora:");

        labelFecha1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        labelFecha1.setText("Fecha:");

        labelSala.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        labelSala.setText("Sala:");

        labelAsiento.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        labelAsiento.setText("Asiento/s:");

        textoPelicula.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        textoHora.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        textoSala.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        textoAsiento.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        textoFecha3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        btnRegresoMenu.setBackground(new java.awt.Color(162, 132, 94));
        btnRegresoMenu.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnRegresoMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresoMenu.setText("Volver al menu principal");
        btnRegresoMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRegresoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresoMenuMouseClicked(evt);
            }
        });

        labelCliente.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        labelCliente.setText("Cliente: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSala)
                                .addGap(18, 18, 18)
                                .addComponent(textoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelHora)
                                    .addGap(18, 18, 18)
                                    .addComponent(textoHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(laberPelicula)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textoPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFecha1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoFecha3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegresoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(etiquetaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCliente)
                                    .addComponent(labelAsiento))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(89, 138, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Titulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoPelicula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(laberPelicula))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelFecha1)
                            .addComponent(textoFecha3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelHora)
                                    .addComponent(textoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(labelSala))
                            .addComponent(textoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAsiento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoAsiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(etiquetaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(labelCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(btnRegresoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresoMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresoMenuMouseClicked
        // TODO add your handling code here:
        control.mostrarMenuPrincipal();
        dispose();
    }//GEN-LAST:event_btnRegresoMenuMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnRegresoMenu;
    private javax.swing.JLabel etiquetaImagen;
    private javax.swing.JLabel labelAsiento;
    private javax.swing.JLabel labelAsiento1;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelFecha1;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelSala;
    private javax.swing.JLabel laberPelicula;
    private javax.swing.JLabel textoAsiento;
    private javax.swing.JLabel textoFecha3;
    private javax.swing.JLabel textoHora;
    private javax.swing.JLabel textoPelicula;
    private javax.swing.JLabel textoSala;
    // End of variables declaration//GEN-END:variables
}
