/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaPresentacion;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author Sebastian Borquez
 */
public class MenuPrincipal extends javax.swing.JFrame {

    //CHECAR EL TAMAÑO DEL MENU PRINCIPAL Y LOS LAYOUTS
    private ControlDeNavegacion control = ControlDeNavegacion.getInstancia();
    private int tamSeparacionbBtns = 15; // Variable que sirve para definir el tamaño de separacion entre los botones
    private String nombrePestania = "CINEMA LERMA"; // Variable para escribir el nombre de la pestaña
    private JPanel panelBotones = new JPanel();

    private int anchoPanelBtns = 200;
    private int alturaPanelBtns = 400;
    private Dimension tamañoPanel = new Dimension(anchoPanelBtns, alturaPanelBtns);
    private int alturaBoton = 200;
    private int anchoBoton = 20;
    private Dimension tamañoBoton = new Dimension(anchoBoton, alturaBoton);

    private JPanel panelCentral = new JPanel();

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setTitle(nombrePestania);
        setSize(640, 830);

        setLocationRelativeTo(null);
        crearEstructuraMenuPrincipal();

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);

        revalidate();
        repaint();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        dibujarLineasDeDiseño(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresoMenu1 = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        btnCuentaMenu = new javax.swing.JButton();
        btnCarteleraMenu = new javax.swing.JButton();
        btnHistorialMenu = new javax.swing.JButton();
        btnSalirMenu = new javax.swing.JButton();
        btnAlimentosMenu = new javax.swing.JButton();
        btnOpcionesMenu1 = new javax.swing.JButton();

        btnRegresoMenu1.setBackground(new java.awt.Color(162, 132, 94));
        btnRegresoMenu1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnRegresoMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresoMenu1.setText("Volver al menu principal");
        btnRegresoMenu1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRegresoMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresoMenu1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 450));
        setMinimumSize(new java.awt.Dimension(450, 450));
        setPreferredSize(new java.awt.Dimension(450, 450));
        setSize(new java.awt.Dimension(450, 450));

        labelTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        labelTitulo.setText("CINEMA LERMA");

        btnCuentaMenu.setBackground(new java.awt.Color(162, 132, 94));
        btnCuentaMenu.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnCuentaMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnCuentaMenu.setText("Cuenta");
        btnCuentaMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCuentaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaMenuActionPerformed(evt);
            }
        });

        btnCarteleraMenu.setBackground(new java.awt.Color(162, 132, 94));
        btnCarteleraMenu.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnCarteleraMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnCarteleraMenu.setText("Cartelera");
        btnCarteleraMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCarteleraMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarteleraMenuMouseClicked(evt);
            }
        });
        btnCarteleraMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarteleraMenuActionPerformed(evt);
            }
        });

        btnHistorialMenu.setBackground(new java.awt.Color(162, 132, 94));
        btnHistorialMenu.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnHistorialMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialMenu.setText("Historial de Compras");
        btnHistorialMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnHistorialMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialMenuActionPerformed(evt);
            }
        });

        btnSalirMenu.setBackground(new java.awt.Color(162, 132, 94));
        btnSalirMenu.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnSalirMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirMenu.setText("Salir");
        btnSalirMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSalirMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMenuMouseClicked(evt);
            }
        });
        btnSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMenuActionPerformed(evt);
            }
        });

        btnAlimentosMenu.setBackground(new java.awt.Color(162, 132, 94));
        btnAlimentosMenu.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnAlimentosMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnAlimentosMenu.setText("Alimentos");
        btnAlimentosMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAlimentosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlimentosMenuActionPerformed(evt);
            }
        });

        btnOpcionesMenu1.setBackground(new java.awt.Color(162, 132, 94));
        btnOpcionesMenu1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnOpcionesMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btnOpcionesMenu1.setText("Opciones");
        btnOpcionesMenu1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpcionesMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionesMenu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAlimentosMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarteleraMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCuentaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalirMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHistorialMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnOpcionesMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCarteleraMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlimentosMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCuentaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOpcionesMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHistorialMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalirMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCuentaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCuentaMenuActionPerformed

    private void btnRegresoMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresoMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresoMenu1ActionPerformed

    private void btnCarteleraMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarteleraMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarteleraMenuActionPerformed

    private void btnHistorialMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialMenuActionPerformed

    private void btnSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirMenuActionPerformed

    private void btnAlimentosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlimentosMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlimentosMenuActionPerformed

    private void btnCarteleraMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarteleraMenuMouseClicked
        // TODO add your handling code here:
        control.mostrarSeleccionarPelicula();
        dispose();

    }//GEN-LAST:event_btnCarteleraMenuMouseClicked

    private void btnSalirMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMenuMouseClicked
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_btnSalirMenuMouseClicked

    private void btnOpcionesMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionesMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpcionesMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlimentosMenu;
    private javax.swing.JButton btnCarteleraMenu;
    private javax.swing.JButton btnCuentaMenu;
    private javax.swing.JButton btnHistorialMenu;
    private javax.swing.JButton btnOpcionesMenu1;
    private javax.swing.JButton btnRegresoMenu1;
    private javax.swing.JButton btnSalirMenu;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables

    private void crearEstructuraMenuPrincipal() {
        setLayout(new BorderLayout());

        labelTitulo.setHorizontalAlignment(SwingConstants.CENTER);
        
        labelTitulo.setFont(new Font("Tw Cen MT Condensed", Font.BOLD, 52));
        labelTitulo.setForeground(Color.BLACK);
        labelTitulo.setBorder(BorderFactory.createEmptyBorder(20, 0, 30, 0));
        
        add(labelTitulo, BorderLayout.NORTH);

        crearEstructuraPanelBotones(panelBotones);

        panelCentral.setPreferredSize(tamañoPanel);
        panelCentral.add(panelBotones, BorderLayout.CENTER);
        add(panelCentral, BorderLayout.CENTER);
        

    }

    private void crearEstructuraPanelBotones(JPanel panelBotones) {
        panelBotones.setPreferredSize(tamañoPanel);
        ajustarTamañoBotones();

        panelBotones.add(btnCarteleraMenu);
        panelBotones.add(btnAlimentosMenu);
        panelBotones.add(btnCuentaMenu);
        panelBotones.add(btnHistorialMenu);
        panelBotones.add(btnOpcionesMenu1);
        panelBotones.add(btnSalirMenu);

        panelBotones.setLayout(new GridLayout(6, 1, 0, tamSeparacionbBtns));
        panelCentral.setBorder(BorderFactory.createEmptyBorder(90, 0, 0, 0));

        panelBotones.setVisible(true);
        panelBotones.revalidate();
        panelBotones.repaint();
    }

    private void ajustarTamañoBotones() {
        btnCarteleraMenu.setPreferredSize(tamañoBoton);
        btnAlimentosMenu.setPreferredSize(tamañoBoton);
        btnCuentaMenu.setPreferredSize(tamañoBoton);
        btnHistorialMenu.setPreferredSize(tamañoBoton);
        btnSalirMenu.setPreferredSize(tamañoBoton);

    }

    private void dibujarLineasDeDiseño(Graphics g) {
        super.paint(g);
        g.setColor(Color.BLACK);
        g.drawLine(0, 150, getWidth(), 150); //Dibujar las lineas de decoracion
        g.drawLine(0, 720, getWidth(), 720);
    }

}
