/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaPresentacion;

import DTOs.FuncionDTO;
import DTOs.PeliculaDTO;
import Excepciones.GestionReservaException;
import java.awt.Color;
import java.awt.Component;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.Month;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicComboBoxUI;
import utilitades.Utilerias;

/**
 *
 * @author Ramon Valencia
 */
public class SeleccionarAsientos extends javax.swing.JFrame {

    private ControlDeNavegacion control = ControlDeNavegacion.getInstancia();
    private Utilerias utilerias = new Utilerias();
    
    private JPanel panelFunciones = new JPanel(new GridLayout(0, 3, 5, 5));

    /**
     * Creates new form SeleccionarAsientos
     */
    public SeleccionarAsientos(LocalDate dia) throws GestionReservaException {
        initComponents();
        PeliculaDTO pelicula = control.consultarPelicula();
        //SEPARAR TODO ESTO EN METODOS, LIBRO CLEAN CODE DIVIDIR TODO ESTO
        jTextAreaDescripcion.setText(pelicula.getDescripcionPelicula());
        //ImageIcon imagen = control.crearImagen(pelicula.getPeliculaImagen(), 200, 300);
        //jLabelImagenPelicula.setIcon(imagen);
        jLabelNombrePelicula.setText(pelicula.getNombrePelicula());
        jTextAreaDescripcion.setEnabled(false);
        jTextFieldNumAsientos.setText("");

//        if (dia.equals(fechaHoy)) {
//            jLabelDia.setText("Hoy");
//        } else if (dia.equals(fechaSegundo)) {
//            jLabelDia.setText(segundoDia);
//        } else if (dia.equals(fechaTercero)) {
//            jLabelDia.setText(tercerDia);
//        } else if (dia.equals(fechaCuarto)) {
//            jLabelDia.setText(cuartoDia);
//        }
    
        generarTablaFunciones(panelFunciones, dia, pelicula);
        generarComboBox(jComboBoxDiaSemana);
        jScrollPane1.setViewportView(panelFunciones);
        revalidate();
        repaint();
        
        

        //QUITAR TODO ESTO, AGREGAR UNA FUNCION EN EL SUBSISTEMA QUE ME DE LAS FECHAS, NO LO HARCODEES
        jComboBoxDiaSemana.addActionListener(e -> {
            String seleccion = (String) jComboBoxDiaSemana.getSelectedItem();
//            if (seleccion == "Hoy") {
//                control.recargarPaginaFunciones(fechaHoy, panelFunciones, pelicula);
//            } else if (seleccion == segundoDia) {
//                control.recargarPaginaFunciones(fechaSegundo, panelFunciones, pelicula);
//            } else if (seleccion == tercerDia) {
//                control.recargarPaginaFunciones(fechaTercero, panelFunciones, pelicula);
//            } else if (seleccion == cuartoDia) {
//                control.recargarPaginaFunciones(fechaCuarto, panelFunciones, pelicula);
//            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jComboBoxDiaSemana = new javax.swing.JComboBox<>();
        jTextFieldNumAsientos = new javax.swing.JTextField();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelDiaSemana = new javax.swing.JLabel();
        jLabelAsientosDisp = new javax.swing.JLabel();
        jLabelCosto = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNumAsientos = new javax.swing.JLabel();
        jLabelImagenPelicula = new javax.swing.JLabel();
        jLabelNombrePelicula = new javax.swing.JLabel();
        jTextAreaDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelDia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setBackground(new java.awt.Color(162, 132, 94));
        btnVolver.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(162, 132, 94));
        btnSiguiente.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
        });
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jComboBoxDiaSemana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jTextFieldNumAsientos.setText("jTextField1");

        jLabelDescripcion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelDescripcion.setText("Descripción: ");

        jLabelDiaSemana.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelDiaSemana.setText("Dia de la Semana");

        jLabelAsientosDisp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelAsientosDisp.setText("Asientos Disponibles: ");

        jLabelCosto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelCosto.setText("Costo Del Boleto: ");

        jLabelTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabelTitulo.setText("Funciones:");

        jLabelNumAsientos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelNumAsientos.setText("Numero De Asientos:");

        jLabelNombrePelicula.setText("jLabel1");

        jTextAreaDescripcion.setText("jLabel1");

        jLabelDia.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelDia.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDiaSemana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCosto)
                            .addComponent(jLabelAsientosDisp)
                            .addComponent(jTextFieldNumAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNumAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jTextAreaDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabelNombrePelicula))
                            .addComponent(jLabelImagenPelicula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jLabelDia))
                .addGap(24, 24, 24)
                .addComponent(jLabelNombrePelicula)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabelImagenPelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDiaSemana)
                            .addComponent(jLabelNumAsientos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNumAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAsientosDisp)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCosto)
                        .addGap(56, 56, 56)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextAreaDescripcion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(264, 264, 264))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        control.mostrarSeleccionarPelicula();
        dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseClicked
        // TODO add your handling code here:
        String texto = jTextFieldNumAsientos.getText();
        FuncionDTO funcion = control.consultarFuncion();
        try {
            control.validarCamposAsientos(texto, funcion);
        } catch (GestionReservaException ex) {
            Logger.getLogger(SeleccionarAsientos.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        int numAsientos = Integer.valueOf(texto);
        control.mostrarSeleccionarMetodoPago(numAsientos);
    }//GEN-LAST:event_btnSiguienteMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> jComboBoxDiaSemana;
    private javax.swing.JLabel jLabelAsientosDisp;
    private javax.swing.JLabel jLabelCosto;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelDiaSemana;
    private javax.swing.JLabel jLabelImagenPelicula;
    private javax.swing.JLabel jLabelNombrePelicula;
    private javax.swing.JLabel jLabelNumAsientos;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldNumAsientos;
    // End of variables declaration//GEN-END:variables

    private void generarTablaFunciones(JPanel panel, LocalDate dia, PeliculaDTO pelicula) throws GestionReservaException {
        Date diaNuevo = new Date();

        if (dia.equals(LocalDate.now())) {
            LocalTime horaActual = LocalTime.now();
            LocalDateTime fechaConHora = LocalDateTime.of(dia, horaActual);
            diaNuevo = Date.from(fechaConHora.atZone(ZoneId.systemDefault()).toInstant());
        } else {
            diaNuevo = Date.from(dia.atStartOfDay(ZoneId.systemDefault()).toInstant());
        }

        List<FuncionDTO> listaFunciones = control.obtenerFunciones(pelicula.getNombrePelicula());
        panel.removeAll();

        for (int i = 0; i < listaFunciones.size(); i++) {
            FuncionDTO funcion = listaFunciones.get(i);
            if (funcion.getFechaHora() == diaNuevo) {
                JButton boton = crearBotonFuncion(funcion, panel);
                panel.add(boton);
            }
        }
    }

    private JButton crearBotonFuncion(FuncionDTO funcion, JPanel panel) {
        
        JButton boton = new JButton();
        Date hora = funcion.getFechaHora();
        
        String funcionMinutos = (funcion.getFechaHora().getMinutes() < 10) ? "0"
                + Integer.toString(funcion.getFechaHora().getMinutes())
                : Integer.toString(funcion.getFechaHora().getMinutes());

        boton.setText(hora.getHours() + ":" + funcionMinutos);
        boton.setBackground(Color.decode("#A2845E"));
        //Aqui se define lo que va a pasar cuando el boton de una funcion sea seleccionado
        boton.addActionListener(e -> {
            SeleccionarAsientos seleccionarAsientos = (SeleccionarAsientos) SwingUtilities.getWindowAncestor(boton);
            seleccionarAsientos.revalidate();
            seleccionarAsientos.repaint();
            
            for (Component componente : panel.getComponents()) {
                if (componente instanceof JButton) { // Verificamos si es un botón
                    componente.setEnabled(true);
                }
            }
            
            boton.setEnabled(false);
            int asientosDisponibles;
            try {
                control.guardarFuncionSeleccionada(funcion);
                asientosDisponibles = control.obtenerAsientosDisponibles(funcion);
                cargarDatos(funcion, asientosDisponibles);
            } catch (GestionReservaException ex) {
                Logger.getLogger(ControlDeNavegacion.class.getName()).log(Level.SEVERE, null, ex);
            }

        });
        return boton;
    }
    
    private void cargarDatos(FuncionDTO funcion, int asientosDisponibles) {
        jLabelCosto.setText("Costo del Boleto: " + String.valueOf(funcion.getPrecio()));
        jLabelAsientosDisp.setText("Asientos Disponibles: " + asientosDisponibles);
    }
    
    private void generarComboBox(JComboBox comboBox) throws GestionReservaException {
        List<Date> fechasFunciones = obtenerFechasFunciones();
        for (int a = 0; a < fechasFunciones.size(); a++) {
            
            crearOpcionComboBox(comboBox, fechasFunciones.get(a));
        }
        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
    }
    
    private List<Date> obtenerFechasFunciones() throws GestionReservaException {
        PeliculaDTO pelicula = control.consultarPelicula();
        List<FuncionDTO> listaFunciones = control.obtenerFunciones(pelicula.getNombrePelicula());
        List<Date> fechasFunciones = new ArrayList<>();
        
        for (int i = 0; i < listaFunciones.size(); i++) {
            FuncionDTO funcion = listaFunciones.get(i);
            Date fecha = funcion.getFechaHora();
            
            if (fechasFunciones.isEmpty()) {
                for (int s = 0; s < fechasFunciones.size(); s++) {
                    if (!fechasFunciones.contains(fecha)) {
                        fechasFunciones.add(fecha);
                    }
                }
            } else {
                System.out.println(fecha);
                fechasFunciones.add(fecha);
            }
        }
        return fechasFunciones;
    }
    
    private void crearOpcionComboBox(JComboBox comboBox, Date dia) {
        
        LocalDate diaLocal = utilerias.convertirDateALocalDate(dia);
        
        String diaTexto = utilerias.traducirDia(diaLocal.getDayOfWeek()) + ", "
            + diaLocal.getDayOfMonth() + " de "
            + utilerias.traducirMes(diaLocal.getMonth());
        comboBox.addItem(diaTexto);
    } 
    

}
