/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaPresentacion;

import DTOs.FuncionDTO;
import DTOs.PeliculaDTO;
import java.awt.Color;
import java.awt.GridLayout;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import utilitades.Utilerias;

/**
 *
 * @author Ramon Valencia
 */
public class SeleccionarAsientos extends javax.swing.JFrame {
    //Instancia de la clase ControlDeNavegacion
    private final ControlDeNavegacion control = ControlDeNavegacion.getInstancia();
    //Objeto necesario para llamar a los metodos de la clase Utilerias
    private final Utilerias utilerias = new Utilerias();
    
    //Se inicializa la pelicula que sera utilizada, sirve para poder consultar la pelicula que fue seleccionada anteriormente
    private final PeliculaDTO pelicula = control.consultarPelicula(); 
    //Se inicializa la Lista de todas Funciones, en base a la pelicula se manda a llamar a un metodo el cual se encarga de obtener las funciones de es pelicula 
    private final List<FuncionDTO> listaFunciones = control.obtenerFunciones(pelicula.getNombrePelicula());
    
    private JPanel panelFunciones = new JPanel();

    /**
     * Creates new form SeleccionarAsientos se inicializa la estructura y se le forma a la a varias partes 
     */
    public SeleccionarAsientos() {
        initComponents();
        
        // Se llama a la funcion que se encarga de darle un formato a la pagina
        generarFormatoPagina();
        // Se llama a la funcion que se encarga de darle un formato al scrollPane donde se ingresaran las funciones
        generarTablaFunciones(jScrollPanel);

        if (panelFunciones.getComponentCount() == 0) {
            SwingUtilities.invokeLater(() -> {
                dispose();
            });
        }

        revalidate();
        repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jTextFieldNumAsientos = new javax.swing.JTextField();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelAsientosDisp = new javax.swing.JLabel();
        jLabelCosto = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNumAsientos = new javax.swing.JLabel();
        jLabelImagenPelicula = new javax.swing.JLabel();
        jLabelNombrePelicula = new javax.swing.JLabel();
        jTextAreaDescripcion = new javax.swing.JLabel();
        jScrollPanel = new javax.swing.JScrollPane();
        jLabelFuncionSeleccionada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setBackground(new java.awt.Color(162, 132, 94));
        btnVolver.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(162, 132, 94));
        btnSiguiente.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
        });
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jTextFieldNumAsientos.setText("jTextField1");

        jLabelDescripcion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelDescripcion.setText("Descripción: ");

        jLabelAsientosDisp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelAsientosDisp.setText("Asientos Disponibles: ");

        jLabelCosto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelCosto.setText("Costo Del Boleto: ");

        jLabelTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabelTitulo.setText("Funciones:");

        jLabelNumAsientos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelNumAsientos.setText("Numero De Asientos:");
        jLabelNumAsientos.setToolTipText("");

        jLabelNombrePelicula.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelNombrePelicula.setText("jLabel1");

        jTextAreaDescripcion.setText("jLabel1");

        jScrollPanel.setPreferredSize(new java.awt.Dimension(250, 150));

        jLabelFuncionSeleccionada.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelFuncionSeleccionada.setText("Funcion seleccionada: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabelNombrePelicula))
                            .addComponent(jLabelImagenPelicula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelFuncionSeleccionada)
                                .addGap(77, 77, 77))
                            .addComponent(jScrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDescripcion)
                            .addComponent(jTextAreaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNumAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCosto)
                                    .addComponent(jLabelAsientosDisp)
                                    .addComponent(jTextFieldNumAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 54, Short.MAX_VALUE)))))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(287, 287, 287))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelTitulo)
                .addGap(27, 27, 27)
                .addComponent(jLabelFuncionSeleccionada)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabelNombrePelicula)
                        .addGap(39, 39, 39)
                        .addComponent(jLabelImagenPelicula)
                        .addGap(18, 105, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumAsientos)
                    .addComponent(jLabelDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextAreaDescripcion))
                .addGap(18, 18, 18)
                .addComponent(jLabelAsientosDisp)
                .addGap(18, 18, 18)
                .addComponent(jLabelCosto)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(264, 264, 264))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        control.mostrarSeleccionarPelicula();
        dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseClicked
        // TODO add your handling code here:
        String texto = jTextFieldNumAsientos.getText();
        FuncionDTO funcion = control.consultarFuncion();
        
        //funcion que se encarga de validar los campos y que aparte de ello regresa el texto validado
        String textoValidado = control.validarCamposAsientos(texto, funcion);
        
        if (textoValidado != null) {
            dispose();
            //Se obtiene el numAsientos y se convierto a entero esto para guardarlo y poder registrarlos mas adelante
            int numAsientos = Integer.valueOf(textoValidado);
            control.guardarNumeroAsientos(numAsientos);
            control.mostrarSeleccionarMetodoPago();

        }

    }//GEN-LAST:event_btnSiguienteMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabelAsientosDisp;
    private javax.swing.JLabel jLabelCosto;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelFuncionSeleccionada;
    private javax.swing.JLabel jLabelImagenPelicula;
    private javax.swing.JLabel jLabelNombrePelicula;
    private javax.swing.JLabel jLabelNumAsientos;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPanel;
    private javax.swing.JLabel jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldNumAsientos;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo para darle formato a la pagina, meterle info a los jText, jLabel y toda la info
     */
    private void generarFormatoPagina() {
        panelFunciones.setLayout(new BoxLayout(panelFunciones, BoxLayout.Y_AXIS));
        jTextAreaDescripcion.setText(pelicula.getDescripcionPelicula());
        //Se llama al metodo de utileria encargado de crear la imagen
        ImageIcon imagen = utilerias.crearImagen(pelicula.getPeliculaImagen(), 200, 300);
        jLabelImagenPelicula.setIcon(imagen);
        jLabelNombrePelicula.setText(pelicula.getNombrePelicula());
        jTextAreaDescripcion.setEnabled(false);
        jTextFieldNumAsientos.setText("");
    }
    
    /**
     * Metodo que recibe el ScrollPanel y el panel y se encarga de meter uno dentro de otro
     * @param scrollPanel
     * @param panel 
     */
    private void generarScrollPanel(JScrollPane scrollPanel, JPanel panel) {
        scrollPanel.setViewportView(panel);
        scrollPanel.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

    }
    
    /**
     * Metodo que se encarga de crear y generar el diseño de los botones de las funciones
     * @param panelBotones
     * @param dia
     * @param diaTexto
     * @return 
     */
    private JPanel generarPanelBotones(JPanel panelBotones, LocalDateTime dia, String diaTexto) {
        panelBotones.setLayout(new GridLayout(2, 0, 10, 10));
        if (listaFunciones != null) {
            //For que se encarga de recorrer las funciones 
            for (int s = 0; s < listaFunciones.size(); s++) {
                FuncionDTO funcion = listaFunciones.get(s);
                //if que se encarga de checar si el dia encaja con la fechaHora de la funcion
                if (funcion.getFechaHora() == dia) {
                    JButton boton = crearBotonFuncion(funcion, diaTexto);

                    panelBotones.add(boton);
                    panelBotones.revalidate();
                    panelBotones.repaint();
                }
            }
        }
        panelBotones.setVisible(true);
        return panelBotones;
    }
    
    /**
     * Metodo que se encarga de generar el panel de cada funcion donde se agrega el texto del dia de la funcion y el boton para seleccionarla
     * 
     * @param panelFuncionDia
     * @param dia
     * @return 
     */
    private JPanel generarPanelFuncionDia(JPanel panelFuncionDia, LocalDateTime dia) {
        //Metodo de utilerias para convertir objeto Date a objeto LocalDate
        
        //Se crea el string para escribir la fecha
        String diaTexto = utilerias.traducirDia(dia.getDayOfWeek()) + ", "
                + dia.getDayOfMonth() + " de "
                + utilerias.traducirMes(dia.getMonth());
        
        
        JLabel labelDia = new JLabel(diaTexto);
        labelDia.setHorizontalAlignment(SwingConstants.CENTER);

        Border borde = BorderFactory.createLineBorder(Color.BLACK, 1);

        labelDia.setBorder(borde);
        
        //En esta parte se le da la forma al panelFuncionDia donde se le agregan el boton y el label
        panelFuncionDia.add(labelDia);
        panelFuncionDia.add(generarPanelBotones(new JPanel(), dia, diaTexto));

        panelFuncionDia.setBorder(borde);

        panelFuncionDia.setVisible(true);
        return panelFuncionDia;
    }
    /**
     * Este metodo es para generar el Panel principal
     * @param panelPrincipal 
     */
    public void generarPanelPrincipal(JPanel panelPrincipal) {
        //Se crea una lista en donde se guardaran las fechas de todas las funciones
        List<LocalDateTime> fechasFunciones = obtenerFechasFunciones();
        //For que se encarga de retirar una fecha y con esa fecha se crea un panel FuncionDia
        for (int i = 0; i < fechasFunciones.size(); i++) {
            LocalDateTime dia = fechasFunciones.get(i);
            panelPrincipal.add(generarPanelFuncionDia(new JPanel(), dia));
        }
        panelPrincipal.setVisible(true);
    }
    
    /**
     * Metodo para generar las tabla las funciones
     * @param scrollPanel 
     */
    private void generarTablaFunciones(JScrollPane scrollPanel) {
        generarPanelPrincipal(panelFunciones);
        generarScrollPanel(scrollPanel, panelFunciones);
    }

    /**
     * Metodo para crear el boton de la funcion
     * @param funcion
     * @param diaTexto
     * @return 
     */
    private JButton crearBotonFuncion(FuncionDTO funcion, String diaTexto) {

        JButton boton = new JButton();
        LocalDateTime hora = funcion.getFechaHora();
        //Utilizando el string de la fecha de la funcion
        String funcionMinutos = (funcion.getFechaHora().getMinute() < 10) ? "0"
                + Integer.toString(funcion.getFechaHora().getMinute())
                : Integer.toString(funcion.getFechaHora().getMinute());

        boton.setText(hora.getHour() + ":" + funcionMinutos);
        boton.setBackground(Color.decode("#A2845E"));
        //Aqui se define lo que va a pasar cuando el boton de una funcion sea seleccionado
        boton.addActionListener(e -> {
            //Se llama a un metodo que se encarga de crear la funcionalidad de un boton
            funcionalidadBoton(boton, funcion, diaTexto);
        });
        boton.setVisible(true);
        return boton;
    }

    /**
     * Metodo para cargar los datos de la funcion en los labels
     * @param funcion
     * @param asientosDisponibles
     * @param diaTexto 
     */
    private void cargarDatos(FuncionDTO funcion, int asientosDisponibles, String diaTexto) {
        jLabelCosto.setText("Costo del Boleto: " + String.valueOf(funcion.getPrecio()));
        jLabelAsientosDisp.setText("Asientos Disponibles: " + asientosDisponibles);
        jLabelFuncionSeleccionada.setText("Funcion seleccionada: " + diaTexto);
    }

    /**
     * Este metodo se encarga de obtener las todas las fechas de cada respectiva funcion
     * @return 
     */
    private List<LocalDateTime> obtenerFechasFunciones() {
        List<LocalDateTime> fechasFunciones = new ArrayList<>();

        if (listaFunciones != null) {
            //For que se encarga de obtene recorrer la lista de funciones 
            for (int i = 0; i < listaFunciones.size(); i++) {
                FuncionDTO funcion = listaFunciones.get(i);
                LocalDateTime fecha = funcion.getFechaHora();
                
                //Aqui se ingresan las fechas y al mismo tiempo se compara para revisar que no se repita ninguna fecha
                if (!fechasFunciones.isEmpty()) {
                    for (int s = 0; s < fechasFunciones.size(); s++) {
                        if (!fechasFunciones.contains(fecha)) {
                            fechasFunciones.add(fecha);
                        }
                    }
                } else {
                    fechasFunciones.add(fecha);
                }
            }
        }
        return fechasFunciones;
    }

    /**
     * Metodo para dar la funcionalidad de un boton
     * @param boton
     * @param funcion
     * @param diaTexto 
     */
    private void funcionalidadBoton(JButton boton, FuncionDTO funcion, String diaTexto) {
        SeleccionarAsientos seleccionarAsientos = (SeleccionarAsientos) SwingUtilities.getWindowAncestor(boton);
        seleccionarAsientos.revalidate();
        seleccionarAsientos.repaint();

        int asientosDisponibles;
        control.guardarFuncionSeleccionada(funcion);
        asientosDisponibles = control.obtenerAsientosDisponibles(funcion);

//        if (asientosDisponibles == 0) {
//            return;
//        }
        cargarDatos(funcion, asientosDisponibles, diaTexto);

    }
}
