/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import DTOs.ClienteDTO;
import control.ControlDeNavegacion;
import control.IControl;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author Sebastian Borquez
 */
public class MenuPrincipalCliente extends javax.swing.JFrame {
    
    private ClienteDTO cliente;

    //CHECAR EL TAMAÑO DEL MENU PRINCIPAL Y LOS LAYOUTS
    private final IControl control = ControlDeNavegacion.getInstancia();
    private final int tamSeparacionbBtns = 15; // Variable que sirve para definir el tamaño de separacion entre los botones
    private final String nombrePestania = "CINEMA LERMA"; // Variable para escribir el nombre de la pestaña
    private final JPanel panelBotones = new JPanel();

    private final int anchoPanelBtns = 200;
    private final int alturaPanelBtns = 400;
    private final Dimension tamañoPanel = new Dimension(anchoPanelBtns, alturaPanelBtns);
    private final int alturaBoton = 40;
    private final int anchoBoton = 200;
    private final Dimension tamañoBoton = new Dimension(anchoBoton, alturaBoton);

    private final JPanel panelCentral = new JPanel();
    
    

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipalCliente() {
        initComponents();
        setTitle(nombrePestania);
        setSize(640, 830);
        setMinimumSize(new java.awt.Dimension(450, 700));

        setLocationRelativeTo(null);
        crearEstructuraMenuPrincipal();

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
        
        this.cliente = control.obtenerClienteActual();

        revalidate();
        repaint();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        dibujarLineasDeDiseño(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresoMenu1 = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        btnCarteleraMenu = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();

        btnRegresoMenu1.setBackground(new java.awt.Color(162, 132, 94));
        btnRegresoMenu1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnRegresoMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresoMenu1.setText("Volver al menu principal");
        btnRegresoMenu1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRegresoMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresoMenu1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 450));
        setSize(new java.awt.Dimension(450, 450));

        labelTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        labelTitulo.setText("CINEMA LERMA");

        btnCarteleraMenu.setBackground(new java.awt.Color(162, 132, 94));
        btnCarteleraMenu.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnCarteleraMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnCarteleraMenu.setText("Cartelera");
        btnCarteleraMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCarteleraMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarteleraMenuMouseClicked(evt);
            }
        });
        btnCarteleraMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarteleraMenuActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(162, 132, 94));
        btnCerrarSesion.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar sesion");
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnEditarUsuario.setBackground(new java.awt.Color(162, 132, 94));
        btnEditarUsuario.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarUsuario.setText("Editar usuario");
        btnEditarUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCarteleraMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditarUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelTitulo)
                .addGap(39, 39, 39)
                .addComponent(btnCarteleraMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 422, Short.MAX_VALUE)
                .addComponent(btnEditarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresoMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresoMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresoMenu1ActionPerformed

    private void btnCarteleraMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarteleraMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarteleraMenuActionPerformed

    private void btnCarteleraMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarteleraMenuMouseClicked
        // TODO add your handling code here:
        control.mostrarSeleccionarPelicula();
        dispose();

    }//GEN-LAST:event_btnCarteleraMenuMouseClicked

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        // TODO add your handling code here:
        control.mostrarIniciarSesion();
        dispose();
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuarioActionPerformed
        // TODO add your handling code here:
        control.mostrarEditarUsuario(this, null, cliente);
    }//GEN-LAST:event_btnEditarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarteleraMenu;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnRegresoMenu1;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables

    private void crearEstructuraMenuPrincipal() {
        setLayout(new BorderLayout());

        labelTitulo.setHorizontalAlignment(SwingConstants.CENTER);

        labelTitulo.setFont(new Font("Tw Cen MT Condensed", Font.BOLD, 52));
        labelTitulo.setForeground(Color.BLACK);
        labelTitulo.setBorder(BorderFactory.createEmptyBorder(20, 0, 30, 0));

        add(labelTitulo, BorderLayout.NORTH);

        crearEstructuraPanelBotones(panelBotones);

        panelCentral.setLayout(new BoxLayout(panelCentral, BoxLayout.Y_AXIS));

        panelCentral.add(Box.createVerticalStrut(110)); 
        panelCentral.add(panelBotones);
        panelCentral.add(Box.createVerticalGlue());

        add(panelCentral, BorderLayout.CENTER);

    }

    private void crearEstructuraPanelBotones(JPanel panelBotones) {
        panelBotones.setLayout(new BoxLayout(panelBotones, BoxLayout.Y_AXIS));

        //Agregar cada boton al panel de botones utilizando boxLayout
        agregarBotonEnBox(btnCarteleraMenu, tamañoBoton, tamSeparacionbBtns, panelBotones);

        panelBotones.setVisible(true);
        panelBotones.revalidate();
        panelBotones.repaint();
    }

    private void dibujarLineasDeDiseño(Graphics g) {
        super.paint(g);
        g.setColor(Color.BLACK);
        //Dibujar las lineas de decoracion
        g.drawLine(0, 150, getWidth(), 150);
        g.drawLine(0, 680, getWidth(), 680);
    }

    private void agregarBotonEnBox(JButton boton, Dimension tamaño, int separacion, JPanel panel) {
        boton.setMaximumSize(tamaño);
        boton.setPreferredSize(tamaño);
        boton.setAlignmentX(Component.CENTER_ALIGNMENT);
        panel.add(boton);
        if (separacion > 0) {
            panel.add(Box.createVerticalStrut(separacion)); //Agregar espacios entre los botones
        }

    }

}
