/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pantallas.reservaBoletos;

import control.ControlDeNavegacion;
import DTOs.MetodoPagoDTO;
import Excepciones.PresentacionException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import utilitades.Utilerias;

/**
 *
 * @author Ramon Valencia
 */
public class SeleccionarMetodoPago extends javax.swing.JDialog {

    private final ControlDeNavegacion control = ControlDeNavegacion.getInstancia();
    private final Utilerias utilerias = new Utilerias();

    /**
     * Creates new form SeleccionarMetodoPago
     */
    public SeleccionarMetodoPago(){
        initComponents();
        generarTablaMetodosPago(panelMetodoPago);
        panelMetodoPago.setVisible(true);
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelMetodoPago = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnVolver.setBackground(new java.awt.Color(162, 132, 94));
        btnVolver.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 64)); // NOI18N
        jLabel1.setText("Selecciona el metodo de pago");

        javax.swing.GroupLayout panelMetodoPagoLayout = new javax.swing.GroupLayout(panelMetodoPago);
        panelMetodoPago.setLayout(panelMetodoPagoLayout);
        panelMetodoPagoLayout.setHorizontalGroup(
            panelMetodoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        panelMetodoPagoLayout.setVerticalGroup(
            panelMetodoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 888, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(panelMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addComponent(panelMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        
        control.mostrarSeleccionarAsientos(control.consultarPelicula());
        dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelMetodoPago;
    // End of variables declaration//GEN-END:variables

    public JPanel generarTablaMetodosPago(JPanel panel) {

        panel.setLayout(new GridLayout(0, 2, 0, 0));
        List<MetodoPagoDTO> metodosPago = control.obtenerMetodosPago();

        panel.removeAll();
        Border border = BorderFactory.createLineBorder(Color.BLACK, 1);

        for (int i = 0; i < metodosPago.size(); i++) {
            MetodoPagoDTO metodoPago = metodosPago.get(i);
            JButton boton = crearBotonMetodoPago(metodoPago.getImagenMetodo(), border, metodoPago.getNombreMetodo());

            JLabel label = new JLabel(metodoPago.getNombreMetodo().toUpperCase());
            label.setBorder(border);
            panel.add(label);
            panel.add(boton);
        }

        return panel;

    }

    private JButton crearBotonMetodoPago(String url, Border border, String nombreMetodo) {
        ImageIcon image = utilerias.crearImagen(url, 50, 50);
        JButton boton = new JButton(image);
        boton.setPreferredSize(new Dimension(150, 50));
        boton.setBorder(border);
        boton.addActionListener(e -> {

            JDialog SeleccionarMetodoPago = (JDialog) SwingUtilities.getWindowAncestor(boton);
            SeleccionarMetodoPago.dispose();

            cambioPestañaBoton(nombreMetodo);
        });
        return boton;
    }

    private void cambioPestañaBoton(String nombreMetodo) {
        String tipo = "";
        switch (nombreMetodo) {
            case "Tarjeta" ->
                tipo = "Tarjeta";
            case "Paypal" ->
                tipo = "Paypal";
            case "Mercado Pago" ->
                tipo = "Mercado";

        }
        try {
            control.mostrarPantallaPago(tipo);
        } catch (PresentacionException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            control.mostrarSeleccionarMetodoPago(control.consultarFuncion());
        }
        
    }

}
