package pantallas.reservaBoletos;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import control.ControlDeNavegacion;
import DTOs.PeliculaDTO;
import DTOs.UsuarioDTO;
import control.IControl;
import enums.Rol;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.IOException;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import utilitades.Utilerias;

/**
 *
 * Clase que crea la pantalla de selección de películas y le da formato, a su
 * vez le da la lógica para su correcto funcionamiento y cargar la cartelera
 * correctamente.
 *
 * @author Daniel Miribe
 */
public final class SeleccionarPelicula extends javax.swing.JFrame {

    //Instancia que nos permite llamar los metodos de control
    private final IControl control = ControlDeNavegacion.getInstancia();

    //Objeto que nos permite invocar a los metodos de utilidades
    private final Utilerias utilidades = new Utilerias();
    
    private List<PeliculaDTO> peliculas;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public SeleccionarPelicula() {
        initComponents();
        
        peliculas = control.obtenerPeliculas();
        
        if (peliculas.isEmpty()) {
            SwingUtilities.invokeLater(() -> {
                dispose();
                regresarPantallaAnterior();
            });
        } else {
            configurarSeleccionarPelicula();
        }
    }
    
    private void configurarSeleccionarPelicula() {
        try {
            // Metodos para cargar todos los elementos necesarios
            getContentPane().setLayout(new BorderLayout());
            
            generarScrollPane(jScrollPane1);
            
            configurarPanelCartelera();
            
            generarCartelera(panelCartelera);
            
            configurarRedimensionamiento();
            
            agregarComponentesAlFrame();
            
            aplicarAjustesFrame();
            
            verificarCarteleraVacia();
        
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, 
                    "ERROR: Hubo un problema al cargar las imagenes de las peliculas. Favor de Intentarlo mas tarde",
                    "¡ERROR!", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Metodo que configura el panel de la cartelera, dandole formato de
     * GridLayout con Scroll.
     */
    private void configurarPanelCartelera() {
        panelCartelera.setLayout(new GridLayout(0, 3, 15, 15));
        panelCartelera.setBackground(Color.BLACK);
        panelCartelera.setAutoscrolls(true);
    }

    /**
     * Metodo que configura el redimensionamiento al cambiar el tamaño de la
     * pantalla, esto para que las peliculas se vean correctamente a cualquier
     * tamaño de pantalla.
     */
    private void configurarRedimensionamiento() {
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                ajustarTamSeleccionPeliculas();
                regenerarCartelera();
            }
        });
    }

    /**
     * Metodo que agrega los componentes necesarios al Frame como titulo,
     * botones, paneles, entre otros.
     */
    private void agregarComponentesAlFrame() {
        JPanel topPanel = new JPanel();
        topPanel.add(Titulo);
        add(topPanel, BorderLayout.NORTH);
        add(jScrollPane1, BorderLayout.CENTER);
        JPanel bottomPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        bottomPanel.add(btnVolver);
        add(bottomPanel, BorderLayout.SOUTH);
    }

    /**
     * Metodo para aplicar ajustes el Frame, tales como tamaño por defecto,
     * tamaño minimo, posicion, entre otros.
     */
    private void aplicarAjustesFrame() {
        setSize(800, 600);
        setMinimumSize(new Dimension(640, 480));
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
    }

    /**
     * Metodo que verifica si la cartelera esta vacia, si es asi se cerrara la
     * pantalla pues no hay nada que mostrar.
     */
    private void verificarCarteleraVacia() {
        if (panelCartelera.getComponentCount() == 0) {
            SwingUtilities.invokeLater(() -> {
                dispose();
            });
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelCartelera = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 64)); // NOI18N
        Titulo.setText("Cartelera");

        btnVolver.setBackground(new java.awt.Color(162, 132, 94));
        btnVolver.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panelCartelera.setAutoscrolls(true);
        panelCartelera.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane1.setViewportView(panelCartelera);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(Titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        regresarPantallaAnterior();
    }//GEN-LAST:event_btnVolverMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCartelera;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo que se encarga de la generacion de la cartelera, recibe un JPanel.
     *
     * @param panel Panel a recibir
     * @throws java.io.IOException
     */
    public void generarCartelera(JPanel panel) throws IOException {
        //Modificacion del JPanel para que sea 3 columnas de botones
        panel.removeAll();

        //Modificacion del tamaño del JPanel
        int columnas = Math.max(3, getWidth() / 250);
        int anchoBoton = (getWidth() - 50) / columnas;

        //En este for se crean los botones, se recorre el arreglo de lista y por cada pelicula se manda a llamar al metodo crear pelicula
        if (peliculas != null) {
            for (PeliculaDTO pelicula : peliculas) {
                //Se llama al metodo para crear el boton
                JButton boton = crearBotonPelicula(pelicula, anchoBoton);
                panel.add(boton);
            }
        }
        panel.setVisible(true);
        panel.revalidate();
        panel.repaint();
    }

    /**
     * Metodo para crear un boton con la imagen de una pelicula.
     *
     * @param pelicula Pelicula dada por el parametro
     * @param ancho Ancho dado por el parametro
     * @return boton Boton con formato completo
     */
    private JButton crearBotonPelicula(PeliculaDTO pelicula, int ancho) throws IOException {
        ImageIcon imagen = utilidades.crearImagen(
                pelicula.getImagen(),
                ancho - 20,
                (int) ((ancho - 20) * 1.5) // 
        );

        // crear boton con diseño adaptable
        JButton boton = new JButton(pelicula.getTitulo(), imagen);
        configurarBoton(boton, ancho);

        // 5. accion del boton
        boton.addActionListener(e -> {
            UsuarioDTO usuario = control.obtenerUsuarioActual();
            if (usuario != null && usuario.getRol() == Rol.ADMINISTRADOR) {
                control.mostrarConsultarFunciones(this, pelicula.getTitulo());
            } else {
                control.mostrarSeleccionarAsientos(pelicula);
            }
            dispose();
        });
        return boton;
    }

    /**
     * Metodo auxiliar que le da formato al boton.
     *
     * @param boton Boton dado por el parametro
     * @param ancho Ancho dado por el parametro
     */
    private void configurarBoton(JButton boton, int ancho) {
        boton.setLayout(new BorderLayout());
        boton.setHorizontalTextPosition(SwingConstants.CENTER);
        boton.setVerticalTextPosition(SwingConstants.BOTTOM);
        Integer tamanioFuente = Math.max(12, ancho / 15);
        boton.setFont(new Font("Arial", Font.BOLD, tamanioFuente));
        boton.setForeground(Color.WHITE);
        boton.setBackground(Color.BLACK);
        boton.setOpaque(true);
        boton.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        boton.setPreferredSize(new Dimension(ancho, (int) (ancho * 1.6)));
    }

    /**
     * Metodo que ajusta el tamaño del scrollPanel donde se encuentran las
     * peliculas.
     */
    private void ajustarTamSeleccionPeliculas() {
        int alturaDisponible = getHeight() - btnVolver.getHeight() - Titulo.getHeight() - 50;
        jScrollPane1.setPreferredSize(new Dimension(panelCartelera.getPreferredSize().width,
                Math.max(alturaDisponible, 300)));
        revalidate();
    }

    /**
     * Metodo que calcula el ancho de los botones.
     *
     * @return El ancho total de un boton
     */
    private int calcularAnchoBotones() {
        int anchoVentana = this.getWidth();
        int margen = 40; // Margen total izquierdo + derecho
        int espacioEntre = 20; // Espacio entre botones
        int columnas = Math.max(3, anchoVentana / 250); // Mínimo 3 columnas
        return (anchoVentana - margen - (columnas - 1) * espacioEntre) / columnas;
    }

    /**
     * Metodo que regenera la cartelera en el panel correspondiente colocando
     * las imagenes en los botones.
     */
    private void regenerarCartelera() {
        int columnas = Math.max(3, getWidth() / 250);
        ((GridLayout) panelCartelera.getLayout()).setColumns(columnas);

        // reconfiguramos todos los botones existentes
        for (Component comp : panelCartelera.getComponents()) {
            if (comp instanceof JButton boton) {
                int nuevoAncho = calcularAnchoBotones();
                boton.setPreferredSize(new Dimension(nuevoAncho, (int) (nuevoAncho * 1.5)));
                
                Integer tamanioFuente = Math.max(12, nuevoAncho / 15);
                
                boton.setFont(new Font("Arial", Font.BOLD, tamanioFuente));
            }
        }
        panelCartelera.revalidate();
        panelCartelera.repaint();
    }

    /**
     * Metodo que genera el scrollPane donde iran las peliculas, generando a su
     * vez los scrolls verticales y horizontales.
     *
     * @param scrollPane Scroll Pane a recibir
     */
    private void generarScrollPane(JScrollPane scrollPane) {
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setBorder(BorderFactory.createEmptyBorder());
    }
    
    private void regresarPantallaAnterior() {
        UsuarioDTO usuario = control.obtenerUsuarioActual();
        if (usuario != null && usuario.getRol() == Rol.CLIENTE) {
            control.mostrarMenuCliente(this);
        } else if (usuario != null && usuario.getRol() == Rol.ADMINISTRADOR) {
            control.mostrarMenuAdministrador(this);
        }
        dispose();
    }

}
