/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Empleados;

import BOs.EmpleadoBO;
import DTOs.EmpleadoDTO;
import Excepciones.ManejoActualizacionEmpleadoException;
import Excepciones.Empleados.ActualizarEmpleadoException;
import Excepciones.Empleados.ValidacionEmpleadoException;
import Excepciones.ManejoObtenerEmpleadoException;
import Excepciones.PersistenciaException;
import Excepciones.ManejoValidacionEmpleadoIdException;
import Excepciones.ManejoValidarEmpleadoException;
import GestionEmpleados.IManejoEmpleados;
import GestionEmpleados.ManejoEmpleados;
import control.ControlDeNavegacion;
import control.IControl;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.bson.types.ObjectId;

/**
 *
 * @author isaac
 */
public class ActualizarEmpleadoDatos extends javax.swing.JFrame {

    private IControl control = ControlDeNavegacion.getInstancia();
    private EmpleadoDTO empleadoActualDTO; // dto del empleado que se edita
    private String empleadoId; // id del empleado que se edita
    

    /**
     * Creates new form ActualizarEmpleadoDatos
     */
    public ActualizarEmpleadoDatos(String empleadoIdParaEditar) throws ManejoValidarEmpleadoException, ManejoObtenerEmpleadoException, ManejoValidacionEmpleadoIdException {
      
        this.empleadoId = empleadoIdParaEditar;
        initComponents();
        configurarFrame();
        cargarDatosEmpleado();
    }

    private void configurarFrame() {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    private void cargarDatosEmpleado() {
        if (this.empleadoId == null || empleadoId.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se especificó un empleado para editar.", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
            return;
        }
        try {
           
            this.empleadoActualDTO = control.consultarEmpleadoActivoPorId(this.empleadoId);

            if (this.empleadoActualDTO == null) {
                JOptionPane.showMessageDialog(this, "Empleado no encontrado o inactivo.", "Error", JOptionPane.ERROR_MESSAGE);
                this.dispose();
                return;
            }

            // Poblar los campos del formulario
            // lblTituloDinamico.setText("Actualizar Datos de: " + empleadoActualDTO.getNombre() + " " + empleadoActualDTO.getApellidoP());
            txtNombre.setText(empleadoActualDTO.getNombre());
            txtApellidoP.setText(empleadoActualDTO.getApellidoP());
            txtApellidoM.setText(empleadoActualDTO.getApellidoM());
            txtCalle.setText(empleadoActualDTO.getCalle());
            txtColonia.setText(empleadoActualDTO.getColonia());
            txtNumExt.setText(empleadoActualDTO.getNumExterior());
            txtCorreoE.setText(empleadoActualDTO.getCorreoE());
            txtTelefono.setText(empleadoActualDTO.getTelefono());

        }
        
         catch (Exception e) { // Otros errores inesperados
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado al cargar los datos: " + e.getMessage(), "Error General", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelApellidoP = new javax.swing.JLabel();
        labelApellidoM = new javax.swing.JLabel();
        labelCorreoE = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelNumExt = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCorreoE = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtNumExt = new javax.swing.JTextField();
        labelColonia = new javax.swing.JLabel();
        labelCalle = new javax.swing.JLabel();
        txtColonia = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        labelTitulo.setText("Actualizar los datos del empleado");

        labelNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNombre.setText("Nombre");

        labelApellidoP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelApellidoP.setText("Apellido paterno");

        labelApellidoM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelApellidoM.setText("Apellido materno");

        labelCorreoE.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCorreoE.setText("Correo electronico");

        labelTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTelefono.setText("Telefono");

        labelNumExt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNumExt.setText("Numero exterior");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtCorreoE.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCorreoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoEActionPerformed(evt);
            }
        });

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        txtApellidoP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPActionPerformed(evt);
            }
        });

        txtApellidoM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMActionPerformed(evt);
            }
        });

        txtNumExt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNumExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumExtActionPerformed(evt);
            }
        });

        labelColonia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelColonia.setText("Colonia");

        labelCalle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCalle.setText("Calle");

        txtColonia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColoniaActionPerformed(evt);
            }
        });

        txtCalle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalleActionPerformed(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(162, 132, 94));
        btnAceptar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(162, 132, 94));
        btnVolver.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelTitulo)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelNombre))
                                        .addGap(70, 70, 70)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelColonia))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelCalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txtCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10))
                                            .addComponent(labelCorreoE, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(168, 168, 168)
                                        .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelNumExt)
                                            .addComponent(txtNumExt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelApellidoP)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnVolver)
                                    .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(45, 45, 45)
                        .addComponent(labelApellidoM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTelefono)
                        .addGap(54, 54, 54)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelTitulo)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(labelColonia)
                    .addComponent(labelCalle)
                    .addComponent(labelCorreoE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelApellidoP)
                            .addComponent(labelTelefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelApellidoM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNumExt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnVolver))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColoniaActionPerformed


    }//GEN-LAST:event_txtColoniaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed


    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPActionPerformed


    }//GEN-LAST:event_txtApellidoPActionPerformed

    private void txtCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalleActionPerformed


    }//GEN-LAST:event_txtCalleActionPerformed

    private void txtCorreoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoEActionPerformed


    }//GEN-LAST:event_txtCorreoEActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed


    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtNumExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumExtActionPerformed


    }//GEN-LAST:event_txtNumExtActionPerformed

    private void txtApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMActionPerformed


    }//GEN-LAST:event_txtApellidoMActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        if (empleadoActualDTO == null) {
            JOptionPane.showMessageDialog(this, "No hay datos de empleado cargados para actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 1. Recolectar datos de los campos (solo los que se pueden modificar)
        String nombre = txtNombre.getText().trim();
        String apellidoP = txtApellidoP.getText().trim();
        String apellidoM = txtApellidoM.getText().trim();
        String calle = txtCalle.getText().trim();
        String colonia = txtColonia.getText().trim();
        String numExt = txtNumExt.getText().trim();
        String correoE = txtCorreoE.getText().trim();
        String telefono = txtTelefono.getText().trim();

        // 2. Crear un DTO con los datos actualizados
        //    Solo incluimos los campos que actualiza tu método actualizarInformacionEmpleado del BO.
        EmpleadoDTO datosNuevosDTO = new EmpleadoDTO();
        datosNuevosDTO.setNombre(nombre);
        datosNuevosDTO.setApellidoP(apellidoP);
        datosNuevosDTO.setApellidoM(apellidoM);
        datosNuevosDTO.setCalle(calle);
        datosNuevosDTO.setColonia(colonia);
        datosNuevosDTO.setNumExterior(numExt);
        datosNuevosDTO.setCorreoE(correoE);
        datosNuevosDTO.setTelefono(telefono);

        // Campos que tu lógica de BO (actualizarInformacionEmpleado) NO actualiza directamente
        // se mantienen del DTO original o se omiten si no son necesarios para esta operación específica.
        datosNuevosDTO.setCargo(empleadoActualDTO.getCargo()); // Mantener cargo original
        datosNuevosDTO.setSueldo(empleadoActualDTO.getSueldo()); // Mantener sueldo original
        datosNuevosDTO.setFechaNacimiento(empleadoActualDTO.getFechaNacimiento()); // Mantener fecha nacimiento original
        // El ID no se pone en el DTO de datosNuevos, se pasa como parámetro separado.

        // 3. Llamar al método de xcontrol
        try {
            EmpleadoDTO empleadoActualizado = control.controlActualizarInformacionEmpleado(this.empleadoId, datosNuevosDTO);

            JOptionPane.showMessageDialog(this, "Datos del empleado actualizados exitosamente.", "Actualización Exitosa", JOptionPane.INFORMATION_MESSAGE);
            this.empleadoActualDTO = empleadoActualizado; // Actualizar el DTO local por si acaso

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado al actualizar: " + e.getMessage(), "Error General", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
       
        control.mostrarActualizarEmpleado(this);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel labelApellidoM;
    private javax.swing.JLabel labelApellidoP;
    private javax.swing.JLabel labelCalle;
    private javax.swing.JLabel labelColonia;
    private javax.swing.JLabel labelCorreoE;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumExt;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtCorreoE;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumExt;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
