/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Empleados;

import BOs.EmpleadoBO;
import DTOs.EmpleadoDTO;
import Excepciones.Empleados.DespedirEmpleadoException;
import Excepciones.PersistenciaException;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author isaac
 */
public class DespedirEmpleados extends javax.swing.JFrame {
    
    private final EmpleadoBO empleadoBO;
    private ListaEmpleados listaEmpleados;

    /**
     * Creates new form DespedirEmpleados
     */
    public DespedirEmpleados() {
        this.empleadoBO = new EmpleadoBO();
        initComponents();
        
        this.listaEmpleados = new ListaEmpleados(this.empleadoBO);
        scrollPanela.setViewportView(this.listaEmpleados); 
        
        //  configuracion adiciones del frame
        setLocationRelativeTo(null); // centrar la ventana
        
        // cargar datos iniciales
        this.listaEmpleados.cargarEmpleadosActivos(); // el panel llama a esto en su constructor
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        scrollPanela = new javax.swing.JScrollPane();
        labelDespedir = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnDetalles = new javax.swing.JButton();
        btnDespedir = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(jScrollPane3);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.PAGE_START);

        labelDespedir.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        labelDespedir.setText("DESPEDIR EMPLEADOS");

        btnVolver.setBackground(new java.awt.Color(162, 132, 94));
        btnVolver.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnDetalles.setBackground(new java.awt.Color(162, 132, 94));
        btnDetalles.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnDetalles.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles.setText("Ver detalles");
        btnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesActionPerformed(evt);
            }
        });

        btnDespedir.setBackground(new java.awt.Color(162, 132, 94));
        btnDespedir.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnDespedir.setForeground(new java.awt.Color(255, 255, 255));
        btnDespedir.setText("Despedir");
        btnDespedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespedirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(scrollPanela, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDetalles)
                .addGap(165, 165, 165)
                .addComponent(btnDespedir)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDespedir)
                .addGap(235, 235, 235))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDespedir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPanela, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnDetalles)
                    .addComponent(btnDespedir))
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
      
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed
        
        EmpleadoDTO seleccionado = listaEmpleados.getEmpleadoSeleccionado();
        if (seleccionado == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un empleado de la lista.", "Selección Requerida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        StringBuilder detalles = new StringBuilder("<html><body><h2>Detalles del Empleado</h2>");
        detalles.append("<b>ID:</b> ").append(seleccionado.getId()).append("<br>");
        detalles.append("<b>Nombre Completo:</b> ").append(seleccionado.getNombre()).append(" ").append(seleccionado.getApellidoP()).append(" ").append(seleccionado.getApellidoM()).append("<br>");
        detalles.append("<b>Correo Electrónico:</b> ").append(seleccionado.getCorreoE()).append("<br>");
        detalles.append("<b>Teléfono:</b> ").append(seleccionado.getTelefono()).append("<br>");
        
        int edad = 0;
        if (seleccionado.getFechaNacimiento() != null) {
            edad = Period.between(seleccionado.getFechaNacimiento().toLocalDate(), LocalDate.now()).getYears();
        }
        detalles.append("<b>Fecha de Nacimiento:</b> ").append(seleccionado.getFechaNacimiento() != null ? seleccionado.getFechaNacimiento().toLocalDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")) : "N/A").append(" (Edad: ").append(edad).append(")<br>");
        detalles.append("<b>Cargo:</b> ").append(seleccionado.getCargo() != null ? seleccionado.getCargo().getDescripcion() : "N/A").append("<br>");
        detalles.append("<b>Sueldo:</b> $").append(String.format("%.2f", seleccionado.getSueldo())).append("<br>");
        detalles.append("<b>Fecha de Registro:</b> ").append(seleccionado.getFechaRegistro() != null ? seleccionado.getFechaRegistro().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")) : "N/A").append("<br>");
        detalles.append("<h3>Dirección</h3>");
        detalles.append("<b>Calle:</b> ").append(seleccionado.getCalle()).append("<br>");
        detalles.append("<b>Colonia:</b> ").append(seleccionado.getColonia()).append("<br>");
        detalles.append("<b>Número Exterior:</b> ").append(seleccionado.getNumExterior()).append("<br>");
        detalles.append("<b>Estado:</b> ").append(seleccionado.isActivo() ? "Activo" : "Inactivo").append("<br>");
        detalles.append("</body></html>");

        JOptionPane.showMessageDialog(this, detalles.toString(), "Detalles de " + seleccionado.getNombre(), JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btnDetallesActionPerformed

    private void btnDespedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespedirActionPerformed
        
        EmpleadoDTO seleccionado = listaEmpleados.getEmpleadoSeleccionado();
        if (seleccionado == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un empleado de la lista.", "Selección Requerida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea despedir al empleado: " + seleccionado.getNombre() + " " + seleccionado.getApellidoP() + "?\nEsta acción lo marcará como inactivo.",
                "Confirmar Despido", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                boolean exito = empleadoBO.despedirEmpleado(seleccionado.getId());
                if (exito) {
                    JOptionPane.showMessageDialog(this, "Empleado despedido (marcado como inactivo) exitosamente.", "Despido Exitoso", JOptionPane.INFORMATION_MESSAGE);
                    listaEmpleados.cargarEmpleadosActivos(); // Actualizar la lista
                } else {
                     JOptionPane.showMessageDialog(this, "El empleado no pudo ser despedido (quizás ya estaba inactivo o no se encontró).", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
            } catch (DespedirEmpleadoException | PersistenciaException ex) {
                JOptionPane.showMessageDialog(this, "Error al despedir empleado: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnDespedirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DespedirEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DespedirEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DespedirEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DespedirEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DespedirEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDespedir;
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelDespedir;
    private javax.swing.JScrollPane scrollPanela;
    // End of variables declaration//GEN-END:variables
}
