/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Empleados;

/**
 *
 * @author isaac
 */
public class MenuEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form MenuEmpleados
     */
    public MenuEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMenu = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnDespedir = new javax.swing.JButton();
        btnGestionCargo = new javax.swing.JButton();
        btnGestionarSueldos = new javax.swing.JButton();
        btnGestionarEmpleados = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 778));
        setSize(new java.awt.Dimension(519, 758));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMenu.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        labelMenu.setText("Administracion de empleados");
        getContentPane().add(labelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        btnRegistrar.setBackground(new java.awt.Color(162, 132, 94));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar empleado");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        btnDespedir.setBackground(new java.awt.Color(162, 132, 94));
        btnDespedir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDespedir.setForeground(new java.awt.Color(255, 255, 255));
        btnDespedir.setText("Despedir empleado");
        getContentPane().add(btnDespedir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        btnGestionCargo.setBackground(new java.awt.Color(162, 132, 94));
        btnGestionCargo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGestionCargo.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionCargo.setText("Gestionar cargos");
        getContentPane().add(btnGestionCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        btnGestionarSueldos.setBackground(new java.awt.Color(162, 132, 94));
        btnGestionarSueldos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGestionarSueldos.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarSueldos.setText("Gestionar sueldos");
        getContentPane().add(btnGestionarSueldos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        btnGestionarEmpleados.setBackground(new java.awt.Color(162, 132, 94));
        btnGestionarEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGestionarEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarEmpleados.setText("Gestionar empleados");
        getContentPane().add(btnGestionarEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, -1, -1));

        btnSalir.setBackground(new java.awt.Color(162, 132, 94));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 600, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDespedir;
    private javax.swing.JButton btnGestionCargo;
    private javax.swing.JButton btnGestionarEmpleados;
    private javax.swing.JButton btnGestionarSueldos;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel labelMenu;
    // End of variables declaration//GEN-END:variables
}
