/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pantallas.Pagos;

import control.ControlDeNavegacion;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import utilitades.Utilerias;

/**
 *
 * @author Ramon Valencia
 */
public class PantallaPagoRechazado extends javax.swing.JDialog {

    private final ControlDeNavegacion control = ControlDeNavegacion.getInstancia();
    private final Utilerias utilerias = new Utilerias();
    
    private final String url = "img/error-icon.png";
    private final int ancho = 200;
    private final int altura = 200;
    
    

    public PantallaPagoRechazado() {
        initComponents();
        ponerImagen(jLabel3, url, ancho, altura);
        
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelimagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCambiarMetodopago = new javax.swing.JButton();
        btnVolverMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 830));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 54)); // NOI18N
        jLabel1.setText("TU PAGO HA SIDO RECHAZADO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel2.setText("Tu pago ha sido rechazado debido a fondos insuficientes o datos incorrectos de tu tarjeta ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, 50));

        btnCambiarMetodopago.setBackground(new java.awt.Color(157, 109, 4));
        btnCambiarMetodopago.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        btnCambiarMetodopago.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarMetodopago.setText("Probar con otro metodo de pago");
        btnCambiarMetodopago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarMetodopagoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiarMetodopago, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, -1));

        btnVolverMenu.setBackground(new java.awt.Color(157, 109, 4));
        btnVolverMenu.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        btnVolverMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverMenu.setText("Volver al menu principal");
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, -1));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 220, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarMetodopagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarMetodopagoActionPerformed
        control.mostrarSeleccionarMetodoPago(control.consultarFuncion());
        dispose();
    }//GEN-LAST:event_btnCambiarMetodopagoActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        control.mostrarMenuPrincipal();
        dispose();
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarMetodopago;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelimagen;
    // End of variables declaration//GEN-END:variables

    private void ponerImagen(JLabel label, String url, int ancho, int altura) {

        ImageIcon imagen = utilerias.crearImagen(url, ancho, altura);
        label.setIcon(imagen);
        label.setText("");
        label.revalidate();
        label.repaint();
        label.setVisible(true);

    }

}
