/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Usuarios;

import DTOs.ClienteDTO;
import control.ControlDeNavegacion;
import control.IControl;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pantallas.MenuPrincipalCliente;

/**
 *
 * @author sonic
 */
public class EditarUsuario extends javax.swing.JFrame {

    private JFrame frameAnterior;
    private ClienteDTO clienteAlMando;

    private ClienteDTO clienteEncontrado;

    private final IControl control = ControlDeNavegacion.getInstancia();

    /**
     * Creates new form EditarUsuario
     */
    public EditarUsuario(JFrame frameAnterior, ClienteDTO clienteEncontrado, ClienteDTO clienteAlMando) {
        initComponents();

        this.clienteAlMando = clienteAlMando;
        this.clienteEncontrado = clienteEncontrado;
        this.frameAnterior = frameAnterior;

        contrasenaField.setVisible(false);
        contrasenalbl.setVisible(false);
        nombreUsuariolbl.setVisible(false);
        nombreUsuarioField.setVisible(false);

        if (clienteAlMando != null) {
            contrasenaField.setVisible(true);
            contrasenalbl.setVisible(true);
            nombreUsuariolbl.setVisible(true);
            nombreUsuarioField.setVisible(true);
        }

        inicializarCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulolbl = new javax.swing.JLabel();
        Nombrelbl = new javax.swing.JLabel();
        ApellidoPaternolbl = new javax.swing.JLabel();
        apellidoMaternolbl = new javax.swing.JLabel();
        callelbl = new javax.swing.JLabel();
        cplbl = new javax.swing.JLabel();
        domiciliolbl = new javax.swing.JLabel();
        botonConfirmar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        domicilioField = new javax.swing.JTextField();
        CalleField = new javax.swing.JTextField();
        CPField = new javax.swing.JTextField();
        apellidoMaternoField = new javax.swing.JTextField();
        nombreField = new javax.swing.JTextField();
        apellidoPaternoField = new javax.swing.JTextField();
        correoField = new javax.swing.JTextField();
        correolbl = new javax.swing.JLabel();
        telefonoField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nombreUsuarioField = new javax.swing.JTextField();
        nombreUsuariolbl = new javax.swing.JLabel();
        contrasenalbl = new javax.swing.JLabel();
        contrasenaField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 820));
        setSize(new java.awt.Dimension(680, 820));

        titulolbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titulolbl.setText("Editar Cliente");

        Nombrelbl.setText("Nombres");

        ApellidoPaternolbl.setText("Apellido Paterno");

        apellidoMaternolbl.setText("Apellido Materno");

        callelbl.setText("Calle");

        cplbl.setText("CP");

        domiciliolbl.setText("Numero de Domicilio");

        botonConfirmar.setBackground(new java.awt.Color(162, 132, 94));
        botonConfirmar.setText("Confirmar cambios");
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(162, 132, 94));
        btnVolver.setText("< Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        correolbl.setText("CorreoElectronico");

        jLabel1.setText("Telefono");

        nombreUsuariolbl.setText("Nombre de usuario");

        contrasenalbl.setText("Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(570, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titulolbl)
                        .addGap(266, 266, 266))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240))))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreUsuariolbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(contrasenalbl)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(nombreUsuarioField)
                                .addGap(88, 88, 88)
                                .addComponent(contrasenaField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Nombrelbl)
                                    .addComponent(apellidoMaternolbl)
                                    .addComponent(callelbl)
                                    .addComponent(CalleField, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(apellidoMaternoField)
                                    .addComponent(nombreField)
                                    .addComponent(correoField)
                                    .addComponent(correolbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ApellidoPaternolbl)
                                    .addComponent(cplbl)
                                    .addComponent(CPField, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(apellidoPaternoField)
                                    .addComponent(domiciliolbl)
                                    .addComponent(domicilioField, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(telefonoField)
                                    .addComponent(jLabel1))))
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titulolbl)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombrelbl)
                    .addComponent(ApellidoPaternolbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidoPaternoField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellidoMaternolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cplbl))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(CPField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidoMaternoField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(callelbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CalleField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(domiciliolbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(domicilioField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correolbl)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(telefonoField, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(correoField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreUsuariolbl)
                    .addComponent(contrasenalbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreUsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contrasenaField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(botonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        // TODO add your handling code here:
        ClienteDTO clienteActualizado = new ClienteDTO();

        if (clienteEncontrado != null) {
            clienteActualizado.setNombreUsuario(clienteEncontrado.getNombreUsuario());
            clienteActualizado.setContraseña(clienteEncontrado.getContraseña());

            clienteActualizado.setNombre(nombreField.getText().trim());
            clienteActualizado.setApellidoPaterno(apellidoPaternoField.getText().trim());
            clienteActualizado.setApellidoMaterno(apellidoMaternoField.getText().trim());
            clienteActualizado.setTelefono(telefonoField.getText().trim());
            clienteActualizado.setCorreoElectronico(correoField.getText().trim());

            clienteActualizado.setCP(CPField.getText().trim());
            clienteActualizado.setCalle(CalleField.getText().trim());
            clienteActualizado.setNumero(domicilioField.getText().trim());

            clienteActualizado.setRol(clienteEncontrado.getRol());
            clienteActualizado.setEstado(clienteEncontrado.getEstado());
            clienteActualizado.setFechaNacimiento(clienteEncontrado.getFechaNacimiento());

        }

        if (clienteAlMando != null) {
            clienteActualizado.setNombreUsuario(nombreUsuarioField.getText().trim());
            clienteActualizado.setContraseña(new String(contrasenaField.getPassword()));

            clienteActualizado.setNombre(nombreField.getText().trim());
            clienteActualizado.setApellidoPaterno(apellidoPaternoField.getText().trim());
            clienteActualizado.setApellidoMaterno(apellidoMaternoField.getText().trim());
            clienteActualizado.setTelefono(telefonoField.getText().trim());
            clienteActualizado.setCorreoElectronico(correoField.getText().trim());

            clienteActualizado.setCP(CPField.getText().trim());
            clienteActualizado.setCalle(CalleField.getText().trim());
            clienteActualizado.setNumero(domicilioField.getText().trim());

            clienteActualizado.setRol(clienteAlMando.getRol());
            clienteActualizado.setEstado(clienteAlMando.getEstado());
            clienteActualizado.setFechaNacimiento(clienteAlMando.getFechaNacimiento());

        }

        if (control.actualizarCliente(clienteActualizado) != null) {
            JOptionPane.showMessageDialog(this, "Cambios guardados correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
            if (frameAnterior instanceof MenuPrincipalCliente) {
                control.mostrarMenuCliente(this, clienteAlMando);
                dispose();
            } else if (frameAnterior instanceof ConsultarUsuarios) {
                control.mostrarGestionDeUsuarios(this, null);
                dispose();
            }
            dispose();

        }

        // **Importante** conservar el nombre de usuario original:

    }//GEN-LAST:event_botonConfirmarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        if (frameAnterior instanceof MenuPrincipalCliente) {
            control.mostrarMenuCliente(this, clienteAlMando);
            dispose();
        } else if (frameAnterior instanceof ConsultarUsuarios) {
            control.mostrarGestionDeUsuarios(this, null);
            dispose();
        }


    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoPaternolbl;
    private javax.swing.JTextField CPField;
    private javax.swing.JTextField CalleField;
    private javax.swing.JLabel Nombrelbl;
    private javax.swing.JTextField apellidoMaternoField;
    private javax.swing.JLabel apellidoMaternolbl;
    private javax.swing.JTextField apellidoPaternoField;
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel callelbl;
    private javax.swing.JPasswordField contrasenaField;
    private javax.swing.JLabel contrasenalbl;
    private javax.swing.JTextField correoField;
    private javax.swing.JLabel correolbl;
    private javax.swing.JLabel cplbl;
    private javax.swing.JTextField domicilioField;
    private javax.swing.JLabel domiciliolbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField nombreUsuarioField;
    private javax.swing.JLabel nombreUsuariolbl;
    private javax.swing.JTextField telefonoField;
    private javax.swing.JLabel titulolbl;
    // End of variables declaration//GEN-END:variables
    private void inicializarCampos() {

        if (clienteEncontrado != null) {
            nombreField.setText(clienteEncontrado.getNombre());
            apellidoPaternoField.setText(clienteEncontrado.getApellidoPaterno());
            apellidoMaternoField.setText(clienteEncontrado.getApellidoMaterno());
            correoField.setText(clienteEncontrado.getCorreoElectronico());
            telefonoField.setText(clienteEncontrado.getTelefono());

            CalleField.setText(clienteEncontrado.getCalle());
            CPField.setText(clienteEncontrado.getCP());
            domicilioField.setText(clienteEncontrado.getNumero());
        }

        if (clienteAlMando != null) {
            nombreField.setText(clienteAlMando.getNombre());
            apellidoPaternoField.setText(clienteAlMando.getApellidoPaterno());
            apellidoMaternoField.setText(clienteAlMando.getApellidoMaterno());
            correoField.setText(clienteAlMando.getCorreoElectronico());
            telefonoField.setText(clienteAlMando.getTelefono());

            CalleField.setText(clienteAlMando.getCalle());
            CPField.setText(clienteAlMando.getCP());
            domicilioField.setText(clienteAlMando.getNumero());

            nombreUsuarioField.setText(clienteAlMando.getNombreUsuario());
            contrasenaField.setText(clienteAlMando.getContraseña());
        }
    }
}
