/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Salas;

import control.ControlDeNavegacion;
import control.IControl;
import enums.EstadoSala;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import utilitades.Utilerias;

/**
 *
 * @author Ramon Valencia
 */
public class AgregarSala extends javax.swing.JFrame {
    
    private final Utilerias utilerias = new Utilerias();
    private final IControl control = ControlDeNavegacion.getInstancia();
    
    private final Integer anchoTxField = 100;
    private final Integer alturaTxField = 25;
    private final Dimension tamTextField = new Dimension(anchoTxField, alturaTxField);
    
    private final Integer anchoBoton = 200;
    private final Integer alturaBoton = 40;
    private final Dimension tamañoBoton = new Dimension(anchoBoton, alturaBoton); 
    private final Font fuenteBoton = new Font("Tw Cen MT Condensed", Font.PLAIN, 20);
    
    private final Color colorBotonFore = new Color(255, 255, 255);

    
    public AgregarSala() {
    utilerias.configurarFrameBase(this, "AGREGAR SALA");
    configurarAgregarSalas();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombreSala = new javax.swing.JLabel();
        labelNumAsientos = new javax.swing.JLabel();
        textFieldNombreSala = new javax.swing.JTextField();
        textFieldNumAsi = new javax.swing.JTextField();
        labelEstado = new javax.swing.JLabel();
        javax.swing.JComboBox<String> comboBoxEstado = new javax.swing.JComboBox<>();
        btnRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNombreSala.setText("Nombre Sala:");

        labelNumAsientos.setText("Numero de Asientos:");

        textFieldNombreSala.setText("jTextField1");

        textFieldNumAsi.setText("jTextField2");

        labelEstado.setText("Estado:");

        comboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRegistro.setText("Registrar Sala");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistro)
                    .addComponent(comboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEstado)
                    .addComponent(textFieldNumAsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNombreSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelNumAsientos, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelNombreSala)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(labelNombreSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNombreSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNumAsientos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNumAsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(btnRegistro)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelNombreSala;
    private javax.swing.JLabel labelNumAsientos;
    private javax.swing.JTextField textFieldNombreSala;
    private javax.swing.JTextField textFieldNumAsi;
    // End of variables declaration//GEN-END:variables
    
    private void configurarAgregarSalas() {
        configurarBotonVolver();
        JPanel panelCampos = new JPanel();
        configurarPanelCampos(panelCampos);
        
        JPanel panelCentral = new JPanel();
        
        panelCentral.setLayout(new BoxLayout(panelCentral, BoxLayout.Y_AXIS));
        
        panelCentral.add(Box.createVerticalStrut(150));
        panelCentral.add(panelCampos);
        panelCentral.add(Box.createVerticalGlue());
        panelCentral.add(Box.createVerticalStrut(300));
        
        add(panelCentral, BorderLayout.CENTER);
        
    }
    
    private void configurarPanelCampos(JPanel panelCampos) {
        panelCampos.setLayout(new BoxLayout(panelCampos, BoxLayout.Y_AXIS));
        
        labelNombreSala = new JLabel("Nombre Sala:");
        textFieldNombreSala = new JTextField();
        textFieldNombreSala.setPreferredSize(tamTextField);
        panelCampos.add(configurarPanelTextField(labelNombreSala, textFieldNombreSala));
        
        labelNumAsientos = new JLabel("Numero de Asientos:");
        textFieldNumAsi = new JTextField();
        textFieldNumAsi.setPreferredSize(tamTextField);
        panelCampos.add(configurarPanelTextField(labelNumAsientos, textFieldNumAsi));
        
        labelEstado = new JLabel("Estado:");
        JComboBox<EstadoSala> comboBoxEstado = new JComboBox<>(EstadoSala.values());
        panelCampos.add(configurarPanelTextField(labelEstado, comboBoxEstado));
        
        btnRegistro = new JButton("Registrar Sala");
        configurarBotonRegistro(btnRegistro);
        panelCampos.add(btnRegistro);
        
    }
    
    /**
     * Metodo para configurar el obtener el boton volver del frameBase y
     * configurarlo para que nos regrese a la ventana anterior
     */
    private void configurarBotonVolver() {
        Container frame = this.getContentPane();
        JPanel panel = (JPanel) frame.getComponent(0);
        JButton btnVolver = (JButton) panel.getComponent(0);

        btnVolver.addActionListener((ActionEvent e) -> {
            control.mostrarMenuSalas(this);
            dispose();
        });

    }
    
    private void configurarBotonRegistro(JButton btnRegistro) {
        btnRegistro.setMaximumSize(tamañoBoton);
        btnRegistro.setPreferredSize(tamañoBoton);
        btnRegistro.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnRegistro.setFont(fuenteBoton);
        btnRegistro.setBackground(Color.BLUE);
        btnRegistro.setForeground(colorBotonFore);
    }
    
    private JPanel configurarPanelTextField(JLabel label, Component componente) {
        JPanel panel = new JPanel();
        panel.add(label);
        panel.add(componente);
        return panel;
    }
}
