/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Salas;

import DTOs.FuncionDTO;
import control.ControlDeNavegacion;
import control.IControl;
import java.awt.Container;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JPanel;
import utilitades.Utilerias;

/**
 *
 * @author Ramon Valencia
 */
public class ConsultarAsientosReservados extends javax.swing.JFrame {

    private final Utilerias utilerias = new Utilerias(); // Objeto Utilerias para poder utilizar los metodos de la clase
    private final IControl control = ControlDeNavegacion.getInstancia(); // Instancia de la clase control de navegacion

    private final FuncionDTO funcionSelecionada;

    /**
     * Creates new form ConsultarAsientosReservados
     *
     * @param funcionSelecionada
     */
    public ConsultarAsientosReservados(FuncionDTO funcionSelecionada) {
        this.funcionSelecionada = funcionSelecionada;
        utilerias.configurarFrameBase(this, "CONSULTAR ASIENTOS");
        configurarConsultarAsientosReservados();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void configurarConsultarAsientosReservados() {
        configurarBotonVolver();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Metodo para configurar el obtener el boton volver del frameBase y
     * configurarlo para que nos regrese a la ventana anterior
     */
    private void configurarBotonVolver() {
        Container frame = this.getContentPane();
        JPanel panel = (JPanel) frame.getComponent(0);
        JButton btnVolver = (JButton) panel.getComponent(0);

        btnVolver.addActionListener((ActionEvent e) -> {
            control.mostrarConsultarFuncionesSalas(this);
        });

    }
}
