/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Salas;

import control.ControlDeNavegacion;
import control.IControl;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import utilitades.ModeladoTablas;
import utilitades.Utilerias;

/**
 *
 * @author Ramon Valencia
 */
public class EstadisticasSala extends javax.swing.JFrame {

    private final IControl control = ControlDeNavegacion.getInstancia();
    private final Utilerias utilerias = new Utilerias();

    private final Integer anchoBuscador = 150;
    private final Integer alturaBuscador = 20;
    private final Dimension tamañoBuscador = new Dimension(anchoBuscador, alturaBuscador);
    private final Map<Integer, Number> tamañoColumnas = Map.of(
            0, 50,
            1, 75,
            2, 90,
            3, 85,
            4, 90
    );
    
    /**
     * Creates new form EstadisticasSala
     */
    public EstadisticasSala() {
        utilerias.configurarFrameBase(this, "ESTADISTICAS");
        configurarEstadisticasSala();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldBuscador = new javax.swing.JTextField();
        labelBuscador = new javax.swing.JLabel();
        labelOrdenamiento = new javax.swing.JLabel();
        comboBoxOrdenamiento = new javax.swing.JComboBox<>();
        botonPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textFieldBuscador.setText("jTextField1");

        labelBuscador.setText("jLabel1");

        labelOrdenamiento.setText("jLabel2");

        comboBoxOrdenamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botonPDF.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBuscador)
                    .addComponent(textFieldBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOrdenamiento))
                .addContainerGap(246, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonPDF)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBuscador)
                    .addComponent(labelOrdenamiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(botonPDF)
                .addGap(221, 221, 221))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void configurarEstadisticasSala() {
        configurarBotonVolver();
        configurarPanelCentral();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPDF;
    private javax.swing.JComboBox<String> comboBoxOrdenamiento;
    private javax.swing.JLabel labelBuscador;
    private javax.swing.JLabel labelOrdenamiento;
    private javax.swing.JTextField textFieldBuscador;
    // End of variables declaration//GEN-END:variables

    private void configurarPanelCentral() {
        JPanel panelCentral = new JPanel();

        JPanel panelBuscador = new JPanel();
        configurarPanelBuscador(panelBuscador);
        JPanel panelTabla = new JPanel();
        configurarPanelTabla(panelTabla);

        panelCentral.setLayout(new BoxLayout(panelCentral, BoxLayout.Y_AXIS));

        panelCentral.add(Box.createVerticalStrut(75));
        panelCentral.add(panelBuscador);
        panelCentral.add(Box.createVerticalGlue());
        panelCentral.add(panelTabla);

        this.add(panelCentral, BorderLayout.CENTER);
    }

    private void configurarPanelBuscador(JPanel panel) {
        JPanel panelBuscador = new JPanel();
        labelBuscador = new JLabel("BUSCAR SALA: ");
        textFieldBuscador = new JTextField();
        textFieldBuscador.setPreferredSize(tamañoBuscador);
        panelBuscador.add(labelBuscador);
        panelBuscador.add(textFieldBuscador);

        JPanel panelOrdenamiento = new JPanel();
        labelOrdenamiento = new JLabel("ORDENAR POR: ");
        configurarComboBoxOrdenamiento();
        panelOrdenamiento.add(labelOrdenamiento);
        panelOrdenamiento.add(comboBoxOrdenamiento);

        panel.add(panelBuscador);
        panel.add(panelOrdenamiento);

    }

    private void configurarComboBoxOrdenamiento() {
        comboBoxOrdenamiento = new JComboBox<>();
        DefaultComboBoxModel<String> modeloComboBox = new DefaultComboBoxModel<>();
        modeloComboBox.addElement("Capacidad");
        modeloComboBox.addElement("Numero de Funciones");
        modeloComboBox.addElement("Ingresos Totales");
        modeloComboBox.addElement("Funciones Canceladas");
        comboBoxOrdenamiento.setModel(modeloComboBox);

        comboBoxOrdenamiento.addActionListener((ActionEvent e) -> {
            //actualizarTabla(comboBoxOrdenamiento.getSelectedItem());
        });

    }

    private void configurarPanelTabla(JPanel panelTabla) {
        String[] columnas = {"SALA", "CAPACIDAD", "<html>NUMERO DE<br>FUNCIONES</html>", "<html>INGRESOS<br>TOTALES</html>", "<html>FUNCIONES<br>CANCELADAS</html>"};
        Object[][] datos = {
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
            {"SALA A1", 25, 12, 1254.9, 45},
        };

        DefaultTableModel modeloTabla = new DefaultTableModel(datos, columnas);
        
        JTable tablaSalas = ModeladoTablas.creacionTablaEstadisticas(columnas, datos);
        
        ModeladoTablas.ajusteTamañoColumnas(tablaSalas, tamañoColumnas);

        JScrollPane scrollPane = new JScrollPane(tablaSalas);
        panelTabla.add(scrollPane);

    }

    /**
     * Metodo para configurar el obtener el boton volver del frameBase y
     * configurarlo para que nos regrese a la ventana anterior
     */
    private void configurarBotonVolver() {
        Container frame = this.getContentPane();
        JPanel panel = (JPanel) frame.getComponent(0);
        JButton btnVolver = (JButton) panel.getComponent(0);

        btnVolver.addActionListener((ActionEvent e) -> {
            control.mostrarMenuSalas(this);
        });

    }
}
