/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Salas;

import control.ControlDeNavegacion;
import control.IControl;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utilitades.Utilerias;

/**
 *
 * @author Ramon Valencia
 */
public final class MenuSalas extends javax.swing.JFrame {

    private final IControl control = ControlDeNavegacion.getInstancia();

    private final int tamSeparacionbBtns = 15; // Variable que sirve para definir el tamaño de separacion entre los botones

    private final int alturaBoton = 40;
    private final int anchoBoton = 300;
    private final Font fuenteBoton = new Font("Tw Cen MT Condensed", Font.BOLD, 24);
    private final Dimension tamañoBoton = new Dimension(anchoBoton, alturaBoton);
    private final Color colorBoton = new Color(162, 132, 94);
    private final Color colorBotonFore = new Color(255, 255, 255);

    private final Utilerias utilerias = new Utilerias();

    public MenuSalas() {

        utilerias.configurarFrameBase(this, "MENU SALAS");
        configurarMenuSalas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregar.setText("Agregar Sala");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEstadisticas.setText("Estadisticas");

        btnModificar.setText("Modificar Sala");

        btnConsultas.setText("Consultar Reservas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConsultas)
                    .addComponent(btnModificar)
                    .addComponent(btnEstadisticas)
                    .addComponent(btnAgregar))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnEstadisticas)
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btnConsultas)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnModificar;
    // End of variables declaration//GEN-END:variables
    public void configurarMenuSalas() {
        configurarBotonVolver();
        JPanel panelBotones = new JPanel();
        crearEstructuraPanelBotones(panelBotones);

        JPanel panelCentral = new JPanel();

        panelCentral.setLayout(new BoxLayout(panelCentral, BoxLayout.Y_AXIS));

        panelCentral.add(Box.createVerticalStrut(110));
        panelCentral.add(panelBotones);
        panelCentral.add(Box.createVerticalGlue());

        add(panelCentral, BorderLayout.CENTER);

    }

    private void crearEstructuraPanelBotones(JPanel panelBotones) {
        panelBotones.setLayout(new BoxLayout(panelBotones, BoxLayout.Y_AXIS));

        //Agregar cada boton al panel de botones utilizando boxLayout
        btnAgregar = new JButton("Agregar Sala");
        configurarBoton(btnAgregar);
        agregarBotonEnBox(btnAgregar, panelBotones);

        btnEstadisticas = new JButton("Estadisticas");
        configurarBoton(btnEstadisticas);
        agregarBotonEnBox(btnEstadisticas, panelBotones);

        btnModificar = new JButton("Modificar Sala");
        configurarBoton(btnModificar);
        agregarBotonEnBox(btnModificar, panelBotones);

        btnConsultas = new JButton("Consultar Reservas");
        configurarBoton(btnConsultas);
        agregarBotonEnBox(btnConsultas, panelBotones);

        panelBotones.setVisible(true);
        panelBotones.revalidate();
        panelBotones.repaint();
    }

    /**
     * Metodo para configurar el obtener el boton volver del frameBase y
     * configurarlo para que nos regrese a la ventana anterior
     */
    public void configurarBotonVolver() {
        Container frame = this.getContentPane();
        JPanel panel = (JPanel) frame.getComponent(0);
        JButton btnVolver = (JButton) panel.getComponent(0);

        btnVolver.addActionListener((ActionEvent e) -> {
            control.mostrarMenuAdministrador(this, null);
            dispose();
        });

    }

    private void agregarBotonEnBox(JButton boton, JPanel panel) {
        panel.add(boton);
        if (tamSeparacionbBtns > 0) {
            panel.add(Box.createVerticalStrut(tamSeparacionbBtns)); //Agregar espacios entre los botones
        }
        String textoBoton = boton.getText();
        boton.addActionListener((ActionEvent e) -> {
            switch (textoBoton) {
                case "Agregar Sala" -> {
                    control.mostrarAgregarSala(this);
                }
                case "Estadisticas" -> {
                    control.mostrarEstadisticasSala(this);
                }
                default ->
                    JOptionPane.showMessageDialog(null, "Hubo un problema para cargar esa ventana intente luego", "INFO", JOptionPane.INFORMATION_MESSAGE);

            }
        });

    }

    private void configurarBoton(JButton boton) {
        boton.setMaximumSize(tamañoBoton);
        boton.setPreferredSize(tamañoBoton);
        boton.setAlignmentX(Component.CENTER_ALIGNMENT);
        boton.setFont(fuenteBoton);
        boton.setBackground(colorBoton);
        boton.setForeground(colorBotonFore);
    }
}
