/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Salas;

import DTOs.SalaViejaDTO;
import control.ControlDeNavegacion;
import control.IControl;
import enums.EstadoSala;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import utilitades.Utilerias;

/**
 *
 * @author Ramon Valencia
 */
public class ModificarSala extends javax.swing.JFrame {
    
    private final IControl control = ControlDeNavegacion.getInstancia();
    private final Utilerias utilerias = new Utilerias();
    private final Font fuente = new Font("Tw Cen MT Condensed", Font.BOLD, 100);
    
    //A continuacion se encuentran las dimensiones para configurar el tamaño del boton para agregar, tambien se configura su fuente y su color
    private final Integer anchoBoton = 200;
    private final Integer alturaBoton = 40;
    private final Dimension tamañoBoton = new Dimension(anchoBoton, alturaBoton);
    private final Font fuenteBoton = new Font("Tw Cen MT Condensed", Font.PLAIN, 20);
    private final Color colorBoton = new Color(162, 132, 94); // Color general del boton

    private final Color colorBotonFore = new Color(255, 255, 255);
    
    private JComboBox<EstadoSala> comboBoxEstado;
    
    private JPanel panelCentral;
    
    private final SalaViejaDTO salaSeleccionada;
    /**
     * Creates new form ModificarSala
     * @param sala
     */
    public ModificarSala(SalaViejaDTO sala) {
        this.salaSeleccionada = sala;
        utilerias.configurarFrameBase(this, "Modificar Sala");
        configurarModificarSala();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardarCambios = new javax.swing.JButton();
        labelNumSala = new javax.swing.JLabel();
        labelCambiarEstado = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        labelNumAsientos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuardarCambios.setText("jButton1");
        btnGuardarCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarCambiosMouseClicked(evt);
            }
        });

        labelNumSala.setText("jLabel1");

        labelCambiarEstado.setText("jLabel2");

        labelEstado.setText("jLabel3");

        labelNumAsientos.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnGuardarCambios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelNumAsientos))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelEstado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(labelNumSala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                        .addComponent(labelCambiarEstado)))
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(labelEstado)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumSala)
                    .addComponent(labelCambiarEstado))
                .addGap(18, 18, 18)
                .addComponent(labelNumAsientos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(btnGuardarCambios)
                .addGap(150, 150, 150))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarCambiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarCambiosMouseClicked
        // TODO add your handling code here:
        String numeroSala = salaSeleccionada.getNumSala();
        EstadoSala estado = (EstadoSala) comboBoxEstado.getSelectedItem();
        Boolean confirmacion = control.modificarSala(numeroSala, estado);
        
        if (confirmacion) {
            SalaViejaDTO sala = control.consultarSala(numeroSala);
            labelEstado.setText("Estado: " + sala.getEstado());
        }
        
    }//GEN-LAST:event_btnGuardarCambiosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JLabel labelCambiarEstado;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelNumAsientos;
    private javax.swing.JLabel labelNumSala;
    // End of variables declaration//GEN-END:variables
    private void configurarModificarSala() {
        configurarPanelCentral();
        configurarBotonVolver();
    }
    
    private void configurarPanelCentral() {
        panelCentral = new JPanel();
        JPanel panelCentralSuperior = new JPanel();
        JPanel panelCentralInferior = new JPanel();
        
        configurarPanelSala(panelCentralSuperior);
        panelCentralSuperior.add(Box.createHorizontalStrut(30));
        configurarPanelEstado(panelCentralSuperior);
        
        configurarPanelInferior(panelCentralInferior);
        
        panelCentralSuperior.setLayout(new FlowLayout(FlowLayout.CENTER));
        
        panelCentral.add(panelCentralSuperior);
        panelCentral.add(panelCentralInferior);
        add(panelCentral, BorderLayout.CENTER);
                
    }
    
    private void configurarPanelSala(JPanel panelCentralSuperior) {
        JPanel panelNumSala = new JPanel();
        
        labelNumSala = new JLabel(
                "<html><div style='text-align:center;'>SALA<br>" 
                + salaSeleccionada.getNumSala() 
                + "</div></html>"
        );
        
        labelNumSala.setFont(fuente);
        panelNumSala.add(labelNumSala);
        panelCentralSuperior.add(panelNumSala);
    }
    
    private void configurarPanelEstado(JPanel panelCentralSuperior) {
        JPanel panelCampos = new JPanel();
        panelCampos.setLayout(new BoxLayout(panelCampos, BoxLayout.Y_AXIS));
        panelCampos.setAlignmentY(Box.CENTER_ALIGNMENT);
        
        labelEstado = new JLabel("Estado: " + salaSeleccionada.getEstado());
        panelCampos.add(Box.createVerticalStrut(10));
        panelCampos.add(labelEstado);
        panelCampos.add(Box.createVerticalStrut(10));
        
        labelCambiarEstado = new JLabel("Cambiar estado:");
        comboBoxEstado = new JComboBox<>(EstadoSala.values());
        panelCampos.add(comboBoxEstado);
        
        labelNumAsientos = new JLabel("Numero de asientos: " + salaSeleccionada.getNumAsientos()
        );
        
        panelCampos.add(Box.createVerticalStrut(10));
        
        panelCampos.add(labelNumAsientos);
        
        panelCampos.add(Box.createVerticalGlue());
        
        panelCentralSuperior.add(panelCampos);
    }
    
    private void configurarPanelInferior(JPanel panelCentralInferior) {
        btnGuardarCambios = new JButton("Guardar Cambios");
        btnGuardarCambios.setPreferredSize(tamañoBoton);
        btnGuardarCambios.setSize(tamañoBoton);
        btnGuardarCambios.setFont(fuenteBoton);
        btnGuardarCambios.setBackground(colorBoton);
        btnGuardarCambios.setForeground(colorBotonFore);
        
        panelCentralInferior.add(Box.createVerticalStrut(400));
        panelCentralInferior.add(btnGuardarCambios);
        panelCentralInferior.add(Box.createGlue());
        
        btnGuardarCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarCambiosMouseClicked(evt);
            }
        });
        
    }
    
    
    /**
     * Metodo para configurar el obtener el boton volver del frameBase y
     * configurarlo para que nos regrese a la ventana anterior
     */
    private void configurarBotonVolver() {
        Container frame = this.getContentPane();
        JPanel panel = (JPanel) frame.getComponent(0);
        JButton btnVolver = (JButton) panel.getComponent(0);
        // Se le añade un action listener para que cierre esta pantalla y abra la anterior
        btnVolver.addActionListener((ActionEvent e) -> {
            control.mostrarSeleccionarSala(this);
            dispose();
        });
    }
}
