/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.administracionPeliculas;

import DTOs.PeliculaDTO;
import control.ControlDeNavegacion;
import control.IControl;
import entidades.Pelicula;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Daniel M
 */
public class AgregarPelicula extends javax.swing.JFrame {

    private final IControl control = ControlDeNavegacion.getInstancia();
    private byte[] imagenSeleccionada;

    /**
     * Creates new form AdministradorPeliculas
     */
    public AgregarPelicula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabelTituloAgregarEditar = new javax.swing.JLabel();
        jlabelImgPromocional = new javax.swing.JLabel();
        jPanelImgPromocional = new javax.swing.JPanel();
        btnSubirImagen = new javax.swing.JButton();
        jlabelTituloPelicula = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jlabelGenero = new javax.swing.JLabel();
        jTextFieldDuracion = new javax.swing.JTextField();
        jlabelClasificacion = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jlabelDuracion = new javax.swing.JLabel();
        jComboBoxClasificacion = new javax.swing.JComboBox<>();
        jTextFieldSinopsis = new javax.swing.JTextField();
        jlabelSinopsis = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlabelTituloAgregarEditar.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jlabelTituloAgregarEditar.setText("Agregar película");

        jlabelImgPromocional.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jlabelImgPromocional.setText("Imágen promocional");

        jPanelImgPromocional.setMaximumSize(new java.awt.Dimension(160, 160));
        jPanelImgPromocional.setMinimumSize(new java.awt.Dimension(160, 160));
        jPanelImgPromocional.setPreferredSize(new java.awt.Dimension(160, 160));

        javax.swing.GroupLayout jPanelImgPromocionalLayout = new javax.swing.GroupLayout(jPanelImgPromocional);
        jPanelImgPromocional.setLayout(jPanelImgPromocionalLayout);
        jPanelImgPromocionalLayout.setHorizontalGroup(
            jPanelImgPromocionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanelImgPromocionalLayout.setVerticalGroup(
            jPanelImgPromocionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        btnSubirImagen.setBackground(new java.awt.Color(162, 132, 94));
        btnSubirImagen.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnSubirImagen.setForeground(new java.awt.Color(255, 255, 255));
        btnSubirImagen.setText("Subir imagen");
        btnSubirImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirImagenActionPerformed(evt);
            }
        });

        jlabelTituloPelicula.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jlabelTituloPelicula.setText("Título");

        jlabelGenero.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jlabelGenero.setText("Seleccionar género");

        jlabelClasificacion.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jlabelClasificacion.setText("Seleccionar clasificación");

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acción", "Aventura", "Ciencia ficción", "Fantasía", "Drama", "Comedia", "Terror", "Suspenso", "Romance", "Animación", "Musical", "Documental", "Crimen", "Histórico", "Biográfico" }));
        jComboBoxGenero.setSelectedIndex(-1);

        jlabelDuracion.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jlabelDuracion.setText("Duración en minutos");

        jComboBoxClasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AA", "A", "B", "B15", "C", "D" }));
        jComboBoxClasificacion.setSelectedIndex(-1);

        jTextFieldSinopsis.setMaximumSize(new java.awt.Dimension(350, 250));
        jTextFieldSinopsis.setMinimumSize(new java.awt.Dimension(350, 250));
        jTextFieldSinopsis.setPreferredSize(new java.awt.Dimension(350, 250));

        jlabelSinopsis.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jlabelSinopsis.setText("Sinopsis");

        btnCancelar.setBackground(new java.awt.Color(162, 132, 94));
        btnCancelar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(162, 132, 94));
        btnAgregar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSubirImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelImgPromocional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jlabelImgPromocional)))
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlabelSinopsis)
                            .addComponent(jlabelDuracion)
                            .addComponent(jlabelClasificacion)
                            .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlabelGenero)
                            .addComponent(jlabelTituloPelicula)
                            .addComponent(jTextFieldTitulo)
                            .addComponent(jComboBoxGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxClasificacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldSinopsis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(262, 262, 262))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlabelTituloAgregarEditar)
                        .addGap(131, 131, 131))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jlabelTituloAgregarEditar)
                .addGap(18, 18, 18)
                .addComponent(jlabelImgPromocional)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelImgPromocional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSubirImagen)
                .addGap(28, 28, 28)
                .addComponent(jlabelTituloPelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlabelGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlabelDuracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlabelClasificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlabelSinopsis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubirImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirImagenActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("jpg", "jpeg", "png"));

        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            try {
                imagenSeleccionada = Files.readAllBytes(archivo.toPath());
                BufferedImage imagen = ImageIO.read(archivo);
                mostrarImagenSeleccionada(imagen);

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al leer la imagen.");
            }
        }
    }//GEN-LAST:event_btnSubirImagenActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        control.mostrarMenuAdministrarPeliculas(this);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregarPelicula();
    }//GEN-LAST:event_btnAgregarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSubirImagen;
    private javax.swing.JComboBox<String> jComboBoxClasificacion;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JPanel jPanelImgPromocional;
    private javax.swing.JTextField jTextFieldDuracion;
    private javax.swing.JTextField jTextFieldSinopsis;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JLabel jlabelClasificacion;
    private javax.swing.JLabel jlabelDuracion;
    private javax.swing.JLabel jlabelGenero;
    private javax.swing.JLabel jlabelImgPromocional;
    private javax.swing.JLabel jlabelSinopsis;
    private javax.swing.JLabel jlabelTituloAgregarEditar;
    private javax.swing.JLabel jlabelTituloPelicula;
    // End of variables declaration//GEN-END:variables

    private void agregarPelicula() {
        String titulo = jTextFieldTitulo.getText();
        String sinopsis = jTextFieldSinopsis.getText();
        String duracionStr = jTextFieldDuracion.getText();
        String genero = (String) jComboBoxGenero.getSelectedItem();
        String clasificacion = (String) jComboBoxClasificacion.getSelectedItem();

        int duracion;
        try {
            duracion = Integer.parseInt(duracionStr);
            if (duracion <= 0) {
                throw new NumberFormatException("Duración inválida");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La duración debe ser un número entero válido mayor a 0.");
            return;
        }

        PeliculaDTO nuevaPeliculaDTO = new PeliculaDTO(imagenSeleccionada, titulo, genero, duracion, clasificacion, sinopsis, true);
        PeliculaDTO exito = control.registrarPelicula(nuevaPeliculaDTO);

        if (exito != null) {
            JOptionPane.showMessageDialog(this, "Película agregada correctamente.");
            control.mostrarMenuAdministrarPeliculas(this);
            dispose();
        }

    }

    private void mostrarImagenSeleccionada(BufferedImage imagen) {

        // Escalar la imagen con aspect ratio al tamaño del panel
        int panelWidth = jPanelImgPromocional.getWidth();
        int panelHeight = jPanelImgPromocional.getHeight();

        int imgWidth = imagen.getWidth();
        int imgHeight = imagen.getHeight();

        // Cálculo del aspect ratio
        double panelRatio = (double) panelWidth / panelHeight;
        double imgRatio = (double) imgWidth / imgHeight;

        int drawWidth, drawHeight;
        if (imgRatio > panelRatio) {
            drawWidth = panelWidth;
            drawHeight = (int) (panelWidth / imgRatio);
        } else {
            drawHeight = panelHeight;
            drawWidth = (int) (panelHeight * imgRatio);
        }

        // Escalar la imagen
        Image imagenEscalada = imagen.getScaledInstance(drawWidth, drawHeight, Image.SCALE_SMOOTH);
        ImageIcon icono = new ImageIcon(imagenEscalada);

        // Limpiar el panel y dibujar la imagen centrada
        jPanelImgPromocional.removeAll();
        jPanelImgPromocional.setLayout(new GridBagLayout()); // Para centrar
        jPanelImgPromocional.add(new JLabel(icono));
        jPanelImgPromocional.revalidate();
        jPanelImgPromocional.repaint();

    }

}
