/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.administracionPeliculas;

import DTOs.PeliculaDTO;
import control.ControlDeNavegacion;
import control.IControl;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import utilitades.RenderizadorImagenPelicula;

/**
 * Clase que representa la pantalla de Agregar Pelicula.
 *
 * Accede a la clase de control de navegacion para navegar entre distintas
 * pantallas del CU y darles funcionamiento.
 *
 * @author Daniel M
 */
public class AgregarPelicula extends javax.swing.JFrame {

    private final IControl control = ControlDeNavegacion.getInstancia();
    private byte[] imagenSeleccionadaBytes;

    /**
     * Constructor de la clase. Inicializa la ventana.
     *
     */
    public AgregarPelicula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jlabelTituloAgregarEditar = new javax.swing.JLabel();
        jlabelImgPromocional = new javax.swing.JLabel();
        jPanelImagenPromocional = new javax.swing.JPanel();
        btnSubirImagen = new javax.swing.JButton();
        jlabelTituloPelicula = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jlabelGenero = new javax.swing.JLabel();
        jTextFieldDuracion = new javax.swing.JTextField();
        jlabelClasificacion = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jlabelDuracion = new javax.swing.JLabel();
        jComboBoxClasificacion = new javax.swing.JComboBox<>();
        jTextFieldSinopsis = new javax.swing.JTextField();
        jlabelSinopsis = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 1000));
        setMinimumSize(new java.awt.Dimension(650, 1000));
        setPreferredSize(new java.awt.Dimension(650, 1000));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelTituloAgregarEditar.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jlabelTituloAgregarEditar.setText("Agregar película");
        getContentPane().add(jlabelTituloAgregarEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jlabelImgPromocional.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jlabelImgPromocional.setText("Imágen promocional");
        getContentPane().add(jlabelImgPromocional, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jPanelImagenPromocional.setMaximumSize(new java.awt.Dimension(160, 160));
        jPanelImagenPromocional.setMinimumSize(new java.awt.Dimension(160, 160));
        jPanelImagenPromocional.setPreferredSize(new java.awt.Dimension(160, 160));

        javax.swing.GroupLayout jPanelImagenPromocionalLayout = new javax.swing.GroupLayout(jPanelImagenPromocional);
        jPanelImagenPromocional.setLayout(jPanelImagenPromocionalLayout);
        jPanelImagenPromocionalLayout.setHorizontalGroup(
            jPanelImagenPromocionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanelImagenPromocionalLayout.setVerticalGroup(
            jPanelImagenPromocionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelImagenPromocional, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, 200));

        btnSubirImagen.setBackground(new java.awt.Color(162, 132, 94));
        btnSubirImagen.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnSubirImagen.setForeground(new java.awt.Color(255, 255, 255));
        btnSubirImagen.setText("Subir imagen");
        btnSubirImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirImagenActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubirImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 160, -1));

        jlabelTituloPelicula.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jlabelTituloPelicula.setText("Título");
        getContentPane().add(jlabelTituloPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));
        getContentPane().add(jTextFieldTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 350, -1));

        jlabelGenero.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jlabelGenero.setText("Seleccionar género");
        getContentPane().add(jlabelGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));
        getContentPane().add(jTextFieldDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 350, -1));

        jlabelClasificacion.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jlabelClasificacion.setText("Seleccionar clasificación");
        getContentPane().add(jlabelClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, -1, -1));

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acción", "Aventura", "Ciencia ficción", "Fantasía", "Drama", "Comedia", "Terror", "Suspenso", "Romance", "Animación", "Musical", "Documental", "Crimen", "Histórico", "Biográfico" }));
        jComboBoxGenero.setSelectedIndex(-1);
        getContentPane().add(jComboBoxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 350, -1));

        jlabelDuracion.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jlabelDuracion.setText("Duración en minutos");
        getContentPane().add(jlabelDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, -1, -1));

        jComboBoxClasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AA", "A", "B", "B15", "C", "D" }));
        jComboBoxClasificacion.setSelectedIndex(-1);
        getContentPane().add(jComboBoxClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 350, -1));

        jTextFieldSinopsis.setMaximumSize(new java.awt.Dimension(350, 250));
        jTextFieldSinopsis.setMinimumSize(new java.awt.Dimension(350, 250));
        jTextFieldSinopsis.setPreferredSize(new java.awt.Dimension(350, 250));
        getContentPane().add(jTextFieldSinopsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 670, -1, 160));

        jlabelSinopsis.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jlabelSinopsis.setText("Sinopsis");
        getContentPane().add(jlabelSinopsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(162, 132, 94));
        btnCancelar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 900, 156, -1));

        btnAgregar.setBackground(new java.awt.Color(162, 132, 94));
        btnAgregar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 850, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento que se ejecuta al presionar el botón "Subir Imagen". Abre un
     * selector de archivos para elegir una imagen desde el sistema. Si se
     * selecciona una imagen válida, se lee en bytes y se muestra en el panel.
     *
     * @param evt Evento de acción generado por el botón
     */
    private void btnSubirImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirImagenActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("jpg", "jpeg", "png"));

        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            try {
                imagenSeleccionadaBytes = Files.readAllBytes(archivo.toPath());
                RenderizadorImagenPelicula.renderizarImagen(jPanelImagenPromocional, imagenSeleccionadaBytes);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al leer la imagen.");
            }
        }
    }//GEN-LAST:event_btnSubirImagenActionPerformed

    /**
     * Evento que se ejecuta al presionar el botón "Cancelar". Regresa al menú
     * de administración de películas y cierra la ventana actual.
     *
     * @param evt Evento de acción generado por el botón
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        control.mostrarMenuAdministrarPeliculas(this);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Evento que se ejecuta al presionar el botón "Agregar". Llama al método
     * que procesa la creación y registro de una nueva película.
     *
     * @param evt Evento de acción generado por el botón
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregarPelicula();
    }//GEN-LAST:event_btnAgregarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSubirImagen;
    private javax.swing.JComboBox<String> jComboBoxClasificacion;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JPanel jPanelImagenPromocional;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldDuracion;
    private javax.swing.JTextField jTextFieldSinopsis;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JLabel jlabelClasificacion;
    private javax.swing.JLabel jlabelDuracion;
    private javax.swing.JLabel jlabelGenero;
    private javax.swing.JLabel jlabelImgPromocional;
    private javax.swing.JLabel jlabelSinopsis;
    private javax.swing.JLabel jlabelTituloAgregarEditar;
    private javax.swing.JLabel jlabelTituloPelicula;
    // End of variables declaration//GEN-END:variables

    /**
     * Obtiene los datos ingresados en el formulario para una nueva película,
     * valida la duración, crea un objeto PeliculaDTO y lo registra en el
     * sistema. Muestra mensajes de éxito o error según el resultado.
     */
    private void agregarPelicula() {
        String titulo = jTextFieldTitulo.getText().trim();
        String sinopsis = jTextFieldSinopsis.getText().trim();
        String duracionStr = jTextFieldDuracion.getText().trim();
        String genero = (String) jComboBoxGenero.getSelectedItem();
        String clasificacion = (String) jComboBoxClasificacion.getSelectedItem();

        int duracion;
        try {
            duracion = Integer.parseInt(duracionStr);
            if (duracion <= 0) {
                throw new NumberFormatException("Duración inválida");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La duración debe ser un número entero válido mayor a 0.");
            return;
        }

        PeliculaDTO nuevaPeliculaDTO = new PeliculaDTO(imagenSeleccionadaBytes, titulo, genero, duracion, clasificacion, sinopsis, true);
        PeliculaDTO exito = control.registrarPelicula(nuevaPeliculaDTO);

        if (exito != null) {
            JOptionPane.showMessageDialog(this, "Película agregada correctamente.");
            control.mostrarMenuAdministrarPeliculas(this);
            dispose();
        }
    }
}
