/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.administracionPeliculas;

import DTOs.AdministradorDTO;
import DTOs.PeliculaDTO;
import control.ControlDeNavegacion;
import control.IControl;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Image;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.ScrollPaneConstants;

/**
 * Clase que representa la pantalla del Menu para Administrar Peliculas.
 *
 * Accede a la clase de control de navegacion para navegar entre distintas
 * pantallas del CU y darles funcionamiento.
 *
 * @author Daniel M
 */
public class MenuAdministrarPeliculas extends javax.swing.JFrame {

    private final IControl control = ControlDeNavegacion.getInstancia();
    private AdministradorDTO administrador;

    /**
     * Crea la interfaz del menú de administración de películas. Carga todas las
     * películas disponibles sin filtros aplicados.
     */
    public MenuAdministrarPeliculas() {
        initComponents();
        cargarPeliculas(control.mostrarPeliculasFiltradas(null, null, null, null));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabelTituloCartelera = new javax.swing.JLabel();
        btnAgregarPelicula = new javax.swing.JButton();
        jComboBoxFiltrarEstado = new javax.swing.JComboBox<>();
        jlabelFiltrar = new javax.swing.JLabel();
        jPanelCarteleraFiltrada = new javax.swing.JPanel();
        jScrollPanePeliculasFiltradas = new javax.swing.JScrollPane();
        btnaVolver = new javax.swing.JButton();
        jlabelGenero = new javax.swing.JLabel();
        jlabelEstado = new javax.swing.JLabel();
        jlabelFiltrar3 = new javax.swing.JLabel();
        jComboBoxFiltrarGenero = new javax.swing.JComboBox<>();
        jComboBoxFiltrarClasificacion = new javax.swing.JComboBox<>();
        jTextFieldFiltrarTitulo = new javax.swing.JTextField();
        jlabelClasificacion = new javax.swing.JLabel();
        btnConfirmarFiltrado = new javax.swing.JButton();
        btnReiniciarFiltros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 880));
        setMinimumSize(new java.awt.Dimension(650, 880));
        setPreferredSize(new java.awt.Dimension(640, 830));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelTituloCartelera.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jlabelTituloCartelera.setText("Administrar Peliculas");
        getContentPane().add(jlabelTituloCartelera, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 22, -1, -1));

        btnAgregarPelicula.setBackground(new java.awt.Color(162, 132, 94));
        btnAgregarPelicula.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnAgregarPelicula.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarPelicula.setText("Agregar pelicula");
        btnAgregarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        jComboBoxFiltrarEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activas", "Inactivas" }));
        jComboBoxFiltrarEstado.setSelectedIndex(-1);
        jComboBoxFiltrarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltrarEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxFiltrarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 250, 134, 53));

        jlabelFiltrar.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jlabelFiltrar.setText("Filtrar por:");
        getContentPane().add(jlabelFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        javax.swing.GroupLayout jPanelCarteleraFiltradaLayout = new javax.swing.GroupLayout(jPanelCarteleraFiltrada);
        jPanelCarteleraFiltrada.setLayout(jPanelCarteleraFiltradaLayout);
        jPanelCarteleraFiltradaLayout.setHorizontalGroup(
            jPanelCarteleraFiltradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanePeliculasFiltradas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );
        jPanelCarteleraFiltradaLayout.setVerticalGroup(
            jPanelCarteleraFiltradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanePeliculasFiltradas, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelCarteleraFiltrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 374, -1, -1));

        btnaVolver.setBackground(new java.awt.Color(162, 132, 94));
        btnaVolver.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnaVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnaVolver.setText("< Volver");
        btnaVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnaVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 790, -1, -1));

        jlabelGenero.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jlabelGenero.setText("Genero:");
        getContentPane().add(jlabelGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 212, -1, -1));

        jlabelEstado.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jlabelEstado.setText("Estado:");
        getContentPane().add(jlabelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 215, -1, -1));

        jlabelFiltrar3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jlabelFiltrar3.setText("Titulo:");
        getContentPane().add(jlabelFiltrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 330, -1, -1));

        jComboBoxFiltrarGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acción", "Aventura", "Ciencia ficción", "Fantasía", "Drama", "Comedia", "Terror", "Suspenso", "Romance", "Animación", "Musical", "Documental", "Crimen", "Histórico", "Biográfico" }));
        jComboBoxFiltrarGenero.setSelectedIndex(-1);
        jComboBoxFiltrarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltrarGeneroActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxFiltrarGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 250, 134, 53));

        jComboBoxFiltrarClasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AA", "A", "B", "B15", "C", "D" }));
        jComboBoxFiltrarClasificacion.setSelectedIndex(-1);
        jComboBoxFiltrarClasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltrarClasificacionActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxFiltrarClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 134, 53));
        getContentPane().add(jTextFieldFiltrarTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 330, 185, 32));

        jlabelClasificacion.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jlabelClasificacion.setText("Clasificacion:");
        getContentPane().add(jlabelClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 214, -1, -1));

        btnConfirmarFiltrado.setBackground(new java.awt.Color(162, 132, 94));
        btnConfirmarFiltrado.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnConfirmarFiltrado.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarFiltrado.setText("Filtrar");
        btnConfirmarFiltrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarFiltradoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarFiltrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 329, -1, -1));

        btnReiniciarFiltros.setBackground(new java.awt.Color(162, 132, 94));
        btnReiniciarFiltros.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnReiniciarFiltros.setForeground(new java.awt.Color(255, 255, 255));
        btnReiniciarFiltros.setText("Limpiar filtros");
        btnReiniciarFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarFiltrosActionPerformed(evt);
            }
        });
        getContentPane().add(btnReiniciarFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 329, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Muestra la pantalla para agregar una nueva película. Cierra la ventana
     * actual.
     */
    private void btnAgregarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPeliculaActionPerformed
        control.mostrarAgregarPelicula(this);
        dispose();
    }//GEN-LAST:event_btnAgregarPeliculaActionPerformed

    private void jComboBoxFiltrarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltrarEstadoActionPerformed

    }//GEN-LAST:event_jComboBoxFiltrarEstadoActionPerformed

    /**
     * Muestra el menú principal del administrador. Cierra la ventana actual.
     */
    private void btnaVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaVolverActionPerformed
        control.mostrarMenuAdministrador(this);
        dispose();
    }//GEN-LAST:event_btnaVolverActionPerformed

    private void jComboBoxFiltrarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltrarGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFiltrarGeneroActionPerformed

    private void jComboBoxFiltrarClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltrarClasificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFiltrarClasificacionActionPerformed

    /**
     * Aplica los filtros seleccionados para mostrar las películas
     * correspondientes. Los filtros incluyen estado, clasificación, género y
     * título.
     */
    private void btnConfirmarFiltradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarFiltradoActionPerformed
        String estadoString = (String) jComboBoxFiltrarEstado.getSelectedItem();
        Boolean estado = null;
        if (estadoString != null) {
            estado = estadoString.equals("Activas");
        }
        String clasificacion = (String) jComboBoxFiltrarClasificacion.getSelectedItem();
        String genero = (String) jComboBoxFiltrarGenero.getSelectedItem();
        String titulo = jTextFieldFiltrarTitulo.getText().trim();
        List<PeliculaDTO> peliculasFiltradas = control.mostrarPeliculasFiltradas(estado, clasificacion, genero, titulo);
        cargarPeliculas(peliculasFiltradas);
    }//GEN-LAST:event_btnConfirmarFiltradoActionPerformed

    /**
     * Reinicia todos los filtros aplicados y recarga la lista completa de
     * películas.
     */
    private void btnReiniciarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarFiltrosActionPerformed
        jComboBoxFiltrarEstado.setSelectedIndex(-1);
        jComboBoxFiltrarClasificacion.setSelectedIndex(-1);
        jComboBoxFiltrarGenero.setSelectedIndex(-1);
        jTextFieldFiltrarTitulo.setText("");
        cargarPeliculas(control.mostrarPeliculasFiltradas(null, null, null, null));
    }//GEN-LAST:event_btnReiniciarFiltrosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPelicula;
    private javax.swing.JButton btnConfirmarFiltrado;
    private javax.swing.JButton btnReiniciarFiltros;
    private javax.swing.JButton btnaVolver;
    private javax.swing.JComboBox<String> jComboBoxFiltrarClasificacion;
    private javax.swing.JComboBox<String> jComboBoxFiltrarEstado;
    private javax.swing.JComboBox<String> jComboBoxFiltrarGenero;
    private javax.swing.JPanel jPanelCarteleraFiltrada;
    private javax.swing.JScrollPane jScrollPanePeliculasFiltradas;
    private javax.swing.JTextField jTextFieldFiltrarTitulo;
    private javax.swing.JLabel jlabelClasificacion;
    private javax.swing.JLabel jlabelEstado;
    private javax.swing.JLabel jlabelFiltrar;
    private javax.swing.JLabel jlabelFiltrar3;
    private javax.swing.JLabel jlabelGenero;
    private javax.swing.JLabel jlabelTituloCartelera;
    // End of variables declaration//GEN-END:variables

    /**
     * Carga una lista de películas en la interfaz gráfica. Cada película se
     * muestra en un panel con su imagen y título. Al hacer clic en alguna, se
     * muestran sus detalles.
     *
     * @param peliculas Lista de películas que se desea mostrar en pantalla.
     */
    private void cargarPeliculas(List<PeliculaDTO> peliculas) {
        JPanel panelContenedor = crearPanelContenedorPeliculas();

        for (PeliculaDTO pelicula : peliculas) {
            JPanel panelPelicula = crearPanelPelicula(pelicula);
            panelContenedor.add(panelPelicula);
        }

        configurarScrollPane(panelContenedor);
    }

    /**
     * Crea y configura el panel contenedor que alojará las películas.
     *
     * @return Un JPanel configurado con layout vertical y fondo blanco.
     */
    private JPanel crearPanelContenedorPeliculas() {
        JPanel panelContenedor = new JPanel();
        panelContenedor.setLayout(new BoxLayout(panelContenedor, BoxLayout.Y_AXIS));
        panelContenedor.setBackground(Color.WHITE); // Fondo blanco
        return panelContenedor;
    }

    /**
     * Crea un panel para una película individual con su imagen, título y evento
     * de clic.
     *
     * @param pelicula Película que se desea representar gráficamente.
     * @return Un JPanel configurado con los datos de la película.
     */
    private JPanel crearPanelPelicula(PeliculaDTO pelicula) {
        JPanel panelPelicula = new JPanel(new BorderLayout());
        panelPelicula.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelPelicula.setBackground(new Color(245, 245, 245)); // Gris clarito

        // Imagen de la película
        JLabel labelImagen = crearLabelImagen(pelicula);

        // Título de la película
        JLabel labelTitulo = new JLabel(pelicula.getTitulo());
        labelTitulo.setFont(new Font("Tw Cen MT Condensed", Font.BOLD, 20));

        // Panel de texto para el título
        JPanel panelTexto = new JPanel(new FlowLayout(FlowLayout.LEFT));
        panelTexto.setOpaque(false); // Fondo transparente
        panelTexto.add(labelTitulo);

        // Agregamos imagen y título al panel de la película
        panelPelicula.add(labelImagen, BorderLayout.WEST);
        panelPelicula.add(panelTexto, BorderLayout.CENTER);

        // Evento al hacer clic sobre la película
        panelPelicula.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        panelPelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                control.mostrarDetallesPelicula(pelicula);
                dispose();
            }
        });

        return panelPelicula;
    }

    /**
     * Crea un JLabel con la imagen de la película redimensionada.
     *
     * @param pelicula Película cuya imagen se desea cargar.
     * @return JLabel con la imagen o un mensaje si no se pudo cargar.
     */
    private JLabel crearLabelImagen(PeliculaDTO pelicula) {
        JLabel labelImagen = new JLabel();
        try {
            ImageIcon icono = new ImageIcon(pelicula.getImagen());
            Image imagen = icono.getImage().getScaledInstance(100, 150, Image.SCALE_SMOOTH);
            labelImagen.setIcon(new ImageIcon(imagen));
        } catch (Exception e) {
            labelImagen.setText("Imagen no encontrada");
        }
        return labelImagen;
    }

    /**
     * Configura el JScrollPane con el panel contenedor de películas.
     *
     * @param panelContenedor Panel con las películas ya generadas.
     */
    private void configurarScrollPane(JPanel panelContenedor) {
        jScrollPanePeliculasFiltradas.setViewportView(panelContenedor);
        jScrollPanePeliculasFiltradas.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPanePeliculasFiltradas.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
    }

}
